### ISSUE TITLE
[Request] Opensearch sink should have option to disable index management

### ISSUE THREAD

**Issue by dbason** [opensearch-project/data-prepper#1051]
**Is your feature request related to a problem? Please describe.**
We are trying to use dataprepper opensearch sink with a minimum set of permissions i.e index permission only.  The destination index is managed by another process.  Currently the sink is trying to do something that requires admin/get, a permission we don't want to assign to our indexing user.

**Describe the solution you'd like**
A config option to disable any template or ism management

**Describe alternatives you've considered (Optional)**
We have considered granting the user more permissions but this is not something we want to do with our use case.

**Comment by asifsmohammed** [comment]
Thanks @dbason for creating the feature request. We'll prioritize this request and get it into 1.4 release. 

If you would like to contribute to this feature to get into 1.3 release, you can also refer to this [Contributing Guidelines](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md#contributing-guidelines) and [Developer Guide](https://github.com/opensearch-project/data-prepper/blob/main/docs/developer_guide.md) to help you get started.

**Comment by dlvenable** [comment]
@dbason , You indicated that you have a system which manages index names for you. Can you share how you would expect Data Prepper to know the current index name? Do you use the current date in the name?

**Comment by dbason** [comment]
> @dbason , You indicated that you have a system which manages index names for you. Can you share how you would expect Data Prepper to know the current index name? Do you use the current date in the name?

It won't need to as we're using ISM.  It should just write to the alias which will then get written to the current write index.

**Comment by dlvenable** [comment]
@dbason ,

I want to run by a possible solution with you.

Data Prepper will introduce a new `index_type` with a value of `management_disabled`. When this is used, Data Prepper will no longer perform the following requests:

* Check whether ISM is enabled or disabled. This requires getting the cluster settings.
* Create an index template
* Get an index template - this was used to see if the version needed an update
* Create an alias index
* Create an index
* Get an index or index alias - this is used to see if it needs to be created
* Create an ISM policy to manage the indices

All Data Prepper should do in this configuration is create bulk document requests and perform search requests (if using the OTelTraceGroupProcessor).

**Comment by LeonD9** [comment]
@dlvenable , Currently what are the permissions necessary for data prepper to be able to create all resources?
