### ISSUE TITLE
Drop Events only when certain conditions are met

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1063]
**Is your feature request related to a problem? Please describe.**

The new `drop` processor drops all Events, but Data Prepper currently doesn't support any form of conditionals. Thus, the `drop` processor probably has little value in 1.3.0.

**Describe the solution you'd like**

The upcoming #1007 Conditional Routing feature is targeted for 1.4.0 and may only cover Sinks then. However, expression parsing ( #1003 ) will be available in 1.3.0. The `drop` processor should have its own custom conditional support for dropping events. I propose adding a `drop_when` condition that only drops events meeting a given condition.

For example, to drop all successful HTTP responses.

```
drop:
  drop_when: "/status_code < 400"
```

**Describe alternatives you've considered (Optional)**

Using the #522 conditional logic would be reasonable. However, Data Prepper efforts are being re-oriented toward Conditional Routing of sinks. And we may reconsider the approach taken for processors.

**Comment by dapowers87** [comment]
This seems reasonable and straight forward to implement once the expression parsing falls into place. We may want to go ahead and implement #816 - Add percentage support - to the drop processor while we are in there. I can see it having value to customers who want a sampling of say error messages but not necessarily want _every_ event sunk.

**Comment by dlvenable** [comment]
Closing this issue in favor of #1105.
