### ISSUE TITLE
[BUG] Indexes otel-v1-apm-span-* are not suitable for Event analytics

### ISSUE THREAD

**Issue by enp** [opensearch-project/data-prepper#1077]
Tried to see otel-v1-apm-span-* indexes created by Data Prepper in OpenSearch Dashboards -> Observability -> Event analytics, but simple request like ```source = otel-v1-apm-span-000001 | fields name``` returns ```Index does not contain a valid time field```

Similar request for indexes created by Jaeger like ```source = jaeger-span-2022-02-21 | fields operationName``` shows results - so why?

I guess the reason is ```startTime``` field format - in ```jaeger-span-*``` indexes it looks as integer (UNUX epoch?), but in ```otel-v1-apm-span-*``` indexes it looks like "2022-02-21T06:04:04.898483Z". Another possible issue is fields names like ```"span.attributes.ci@pipeline@run@url"``` in ```otel-v1-apm-span-*``` indexes, which looks less usable than similar data in ```jaeger-span-*``` indexes

**Comment by sshivanii** [comment]
Hi @enp 
Confirmed this from the OpenSearch Dashboards team, Event Analytics does not support nano time but they will support date nanos in the upcoming release.
