### ISSUE TITLE
Add null support to DataPrepperExpressions

### ISSUE THREAD

**Issue by sbayer55** [opensearch-project/data-prepper#1136]
**Is your feature request related to a problem? Please describe.**
Today if a JsonPointer results in a null value an exception is thrown. Using [Data Prepper Expression Syntax](https://github.com/opensearch-project/data-prepper/issues/1005) null values cannot be hard coded. As of Data Prepper 1.3.0 all operators are not null safe.

**Describe the solution you'd like**
Add support for a `null` keyword.

Example:
```
/status_code in {null, 400, 404}
```

**Describe alternatives you've considered (Optional)**
Handling null values with exceptions.

**Additional context**
n/a

**Comment by kkondaka** [comment]
We will support equal and not-equal operators with "null" keyword initially. Support for "in" operator may be added later.

**Comment by dlvenable** [comment]
Closed by #1946
