### ISSUE TITLE
Remove ExportTraceServiceRequest record type as Data Prepper supported internal data type.

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#1272]
**Is your feature request related to a problem? Please describe.**
Data Prepper trace ingestion is now supporting record_type:event which uses Event as data model and flow unit processed by trace ingestion plugins. The classic data unit record_type:otlp which indicates ExportTraceServiceRequest as data model will be removed in 2.0. 

**Describe the solution you'd like**

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by dlvenable** [comment]
The current documentation states the new approach to configuring a pipeline: https://opensearch.org/docs/latest/clients/data-prepper/pipelines/#event-record-type

It suggests:

```
source:
    otel_trace_source:
      ssl: false
      record_type: event
```

If we keep the `record_type` such that it has only one option: `event`, then a pipeline author can configure a pipeline in 1.5 and have it work in 2.0 without having to make changes to the pipeline. This provides a nice migration path.

**Comment by chenqi0805** [comment]
> Thoughts on keeping record_type versus removing it entirely?

I lean towards removing it entirely as it provides no additional value for user. But I agree we should document that thoroughly in https://github.com/opensearch-project/documentation-website

**Comment by chenqi0805** [comment]
documentation update PR: https://github.com/opensearch-project/documentation-website/pull/1306

**Comment by chenqi0805** [comment]
Closed via the PR merged above
