### ISSUE TITLE
Kubernetes deployment readiness probe and liveness probe

### ISSUE THREAD

**Issue by wwwlll2001** [opensearch-project/data-prepper#1314]
just want to know how to perform health check for Data prepper, thanks

**Comment by asifsmohammed** [comment]
Thanks @wwwlll2001 for creating the issue. 

You can perform gRPC health check for OTel Trace Source if you enabled it in the [configuration](https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins/otel-trace-source#configurations) using `health_check_service`.

If you are looking for health check for Data Prepper, we don't have any health check in-place.  

To understand the requirement better, can you please tell what's the level of robustness of health check you are expecting? Or is it just to know if Data Prepper is up?

**Comment by wwwlll2001** [comment]
@asifsmohammed  thanks for your reponse

During these several months, data-prepper has stopped serviced several times silently, sometime is caused by OOM, sometime is by "forcing terminating", and the result is the same,  the otel collector could not send trace to data prepper  as data prepper did not response anymore although it's up but actually not working, so i wonder whether there are such health check to detect whether data prepper is working normally, if not, we could kill it and then restart it

hope to get more advice, thanks

**Comment by wwwlll2001** [comment]
@asifsmohammed 
I think i understand what is the health check for OTel Trace Source, in my understanding , if the health check fails, then the data prepper has stopped service for handling otel trace, so that we can take action such as restart or some others.

Am I right?

**Comment by asifsmohammed** [comment]
Yes, that's right. If OTel Trace Source health check fails then the Data Prepper has stopped service. 

You can also try [http://localhost:4900/list](http://localhost:4900/list) to get the list of pipelines to find if the Data Prepper is up.  But this doesn't indicate if source's or sinks have stopped.

**Comment by cmanning09** [comment]
Thanks for your question @wwwlll2001 

I am going to close this issue now that @asifsmohammed has answered it. If you still need further clarification please re-open the issue.
