### ISSUE TITLE
Support customized common metric tags in Data Prepper configuration

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#1415]
**Is your feature request related to a problem? Please describe.**
Currently Data Prepper reserves serviceName as its single common tag key with its value configurable through environment variable. This tag will be attached to any Data Prepper plugin metrics. Users are restricted to configure that single tag value for Data Prepper monitoring.

**Describe the solution you'd like**
We should allow users to customize the common metric tag key-value pairs in data-prepper-config.yaml as follows:

```
commonMetricTags:
   - key1: value1
   - key2: value2
   - ...
```

The commonMetricTags is an optional field defaults to empty list. The number of key value pairs after deduplication will be restricted to a max limit as for cloudwatch/embedded metrics format meter registry, tags will be converted into dimensions. The max allowed number of dimensions for a metric is 9 and we still want to reserve rooms for individual plugin to add special tags for its metrics(e.g. peer-forwarder has endpoint as tag for some of its metrics). 

The initial max limit will be set to 3. A conservative number that we can increase later.

On the other hand, for backward compatibility, serviceName will remain as a reserved tag key that must be configured via environment variable until full removal in 2.0 release.

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by dlvenable** [comment]
Thanks for this proposal, @chenqi0805. It looks good. I do have a question about the name. Why did you choose `commonMetricTags` instead of `metricTags`?

Also, per #291, Data Prepper is aiming for snake_case over camelCase. So perhaps either `common_metric_tags` or `metric_tags` would be better. Thoughts?

**Comment by chenqi0805** [comment]
> Thanks for this proposal, @chenqi0805. It looks good. I do have a question about the name. Why did you choose `commonMetricTags` instead of `metricTags`?

`commonMetricTags` is meant for distinguishing from specialized tags added by specific meters. e.g. in PeerForwarder
```
final Timer forwardRequestTimer = forwardRequestTimers.computeIfAbsent(
                peerIp, ip -> pluginMetrics.timerWithTags(LATENCY, DESTINATION, ip));
```
(DESTINATION, ip) is a specialized tag only belongs to the forward request LATENCY metric. But I am OK with removal of "common" prefix if it does not add value.

> Also, per #291, Data Prepper is aiming for snake_case over camelCase. So perhaps either `common_metric_tags` or `metric_tags` would be better. Thoughts?

Thanks for pointing me to the issue of normalization. Currently, `meterRegistries` is a data-prepper config parameter still in camelCase. I will stick with snake_case for addressing this issue.
