### ISSUE TITLE
Remove AWS SDK v1 from S3 Source

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1562]
**Is your feature request related to a problem? Please describe.**

The S3 Source imports `aws-java-sdk-s3` v1 in order to use the S3 Event Notification model. This adds unnecessary dependencies into Data Prepper.

**Describe the solution you'd like**

Create an internal model representation of the S3 Event Notification structure. Use Jackson's [`@JsonIgnoreProperties`](https://fasterxml.github.io/jackson-annotations/javadoc/2.9/com/fasterxml/jackson/annotation/JsonIgnoreProperties.html#ignoreUnknown()) so that we can model only the parts we need.

**Comment by jzonthemtn** [comment]
@dlvenable I can take this one. Then I'll try to stop taking your "good first issue" ones. :)

**Comment by dlvenable** [comment]
Thanks @jzonthemtn ! Feel free to take as many "good first issue" items as you'd like. :)

**Comment by dlvenable** [comment]
Resolved in #1628 .
