### ISSUE TITLE
Eliminate null checks required by PluginSetting clients.

### ISSUE THREAD

**Issue by cmanning09** [opensearch-project/data-prepper#1563]
**Is your feature request related to a problem? Please describe.**
`PluginSettings` can return null items when fetching configurations. This requires every plugin to perform null checks. 

**Describe the solution you'd like**
Null checking is an anti-pattern and can be eliminated through the use of optionals or returning default values.

**Additional context**
Raised from #1560

**Comment by cmanning09** [comment]
@dlvenable - what is the long term vision for the PluginSettings class? Is it on the for deprecation with the plugin refactoring?

If it is not, I think this has the potential to be a good first issue

**Comment by dlvenable** [comment]
@cmanning09 , Unless you object, I'd like to close this issue and deprecate `PluginSettings` as described in #2000.

**Comment by dlvenable** [comment]
I'm closing this in favor #2000.
