### ISSUE TITLE
Add Duration support for Data Prepper Configuration using PluginDurationDeserializer

### ISSUE THREAD

**Issue by asifsmohammed** [opensearch-project/data-prepper#1623]
**Is your feature request related to a problem? Please describe.**
Currently, only piplelines.yaml can be deserialized using [PluginDurationDeserializer](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/PluginDurationDeserializer.java). It doesn't allow `DataPrepperConfiguration` to use `Duration`.

**Describe the solution you'd like**
One solution I could think of is make `PluginDurationDeserializer` a generic class instead of just for plugins and make it public. We can configure the object mapper of [DataPrepperAppConfiguration](https://github.com/opensearch-project/data-prepper/blob/e1b0e4162a12c11aecef6243188348e271ad9323/data-prepper-core/src/main/java/com/amazon/dataprepper/parser/config/DataPrepperAppConfiguration.java#L50) here with custom deserializer.

**Comment by dlvenable** [comment]
Additionally, this can formalize the concept of a "Data Prepper duration". This is an input string that can be in the format of either an ISO-8601 string or expressed as "Ns" or "Nms" for a specified second or millisecond value.

**Comment by asifsmohammed** [comment]
Fixed as part of https://github.com/opensearch-project/data-prepper/pull/1757
