### ISSUE TITLE
Add support in Http Source to enable TLS/SSL using certificate and private key from AWS Certificate Manager (ACM)

### ISSUE THREAD

**Issue by dinujoh** [opensearch-project/data-prepper#1670]
**Is your feature request related to a problem? Please describe.**
Add support in Http Source to enable TLS/SSL using certificate and private key from AWS Certificate Manager (ACM) similar to ACM support in [OTel Trace Source](https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins/otel-trace-source#ssl)

**Describe the solution you'd like**
Follow similar approach as OTel Trace Source.

**Describe alternatives you've considered (Optional)**
None

**Additional context**
We already support ACM integration in OTel Trace Source, so ACM support for Log Source will help keep SSL configuration consistent across different source.

**Comment by dlvenable** [comment]
This will implement part of #365.
