### ISSUE TITLE
Make Peer Forwarding secure by default

### ISSUE THREAD

**Issue by asifsmohammed** [opensearch-project/data-prepper#1699]
Currently core peer forwarder has a limitation of creating beans with ssl as true by default. 

Solution 1:
Make ssl false by default.
Solution 2: 
Have a configuration with default values for ssl certificate file and key file.
Solution 3:
Make Data Prepper use a configuration file while building beans where ssl is disabled.

**Comment by dlvenable** [comment]
When the peer-forwarder runs, we can enable SSL by default. I also suggest that the default SSL be to look into the `config/` directory for known file names.

Perhaps: `config/certificate.pem` and `config.private_key.pem`? I'm open to other names.

We can bundle Data Prepper with predefined values here. These can also be used by the Data Prepper server, OTel server, HTTP server, etc.

**Comment by dlvenable** [comment]
This should include using Mutual TLS for authentication by default as well.

**Comment by dlvenable** [comment]
It might be better to use a different name by default which clarifies that the certificate is the default one.

Perhaps:

```
config/default_certificate.pem
config/default_private_key.pem
```
