### ISSUE TITLE
Prevent Processor-Level Data Loss on Pipeline Shutdown

### ISSUE THREAD

**Issue by engechas** [opensearch-project/data-prepper#1770]
The shutdown behavior of a few of the Processors could cause data loss/unintended behavior.

**Grok Processor**
The Grok Processor [calls shutdown on its local ExecutorService](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/grok-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/grok/GrokPrepper.java#L146) in the `prepareForShutdown` method. This occurs before the `ProcessWorker`s are shutdown. Grok Processor configurations that specify a timeout would encounter an exception before the buffer data is cleared as no new tasks can be submitted to the Grok Processor's ExecutorService since it was already shutdown.

**Otel Trace Raw Processor**
The Otel Trace Raw Processor sets an `isShuttingDown` boolean to true as part of its `prepareForShutdown` method. This will cause all traces to be flushed due as [shouldGarbageCollect() now evaluates to true](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/otel-trace-raw-processor/src/main/java/com/amazon/dataprepper/plugins/processor/oteltrace/OTelTraceRawProcessor.java#L220). This is the correct behavior when the buffer is empty and the ProcessWorker's run method is in its final iteration. However, if the buffer is not empty, then multiple calls to the Otel Trace Raw Processor will be made with `isShuttingDown` set to true, prematurely flushing traces.

**Aggregate Processor**
The Aggregate Processor [does not have shutdown behavior implemented](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessor.java#L116-L129) which will result in any partial aggregation data being dropped on pipeline shutdown.

**Service Map Stateful Processor**
The Service Map Stateful Processor sets the [previousTimestamp to 0 in its prepareForShutdown method](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/service-map-stateful/src/main/java/com/amazon/dataprepper/plugins/prepper/ServiceMapStatefulPrepper.java#L271). This causes the window to be closed and the data flushed in the next `doExecute()` iteration which is the correct behavior if the buffer is empty. However the `rotateWindow()` method is also invoked which resets the `previousTimestamp`, thereby opening another window. If `doExecute()` must be invoked again as the buffer is not yet empty, then `prepareForShutdown()` method will have been for nothing and the window duration must be observed and flushed before the [isReadyForShutdown method](https://github.com/opensearch-project/data-prepper/blame/main/data-prepper-plugins/service-map-stateful/src/main/java/com/amazon/dataprepper/plugins/prepper/ServiceMapStatefulPrepper.java#L276) will evaluate to true and allow the ProcessWorkers to terminate. If the `processorShutdownTimeout` expires before the new window is flushed, that data will be dropped.

**Comment by engechas** [comment]
Proposed solution for the Grok Processor - move the the ExecutorService shutdown and awaitTermination calls to the `shutdown()` method so that the shutdown-related methods become:
```
@Override
public void prepareForShutdown() {
    
}

@Override
public boolean isReadyForShutdown() {
    return true;
}

@Override
public void shutdown() {
    executorService.shutdown();
    try {
        if (executorService.awaitTermination(300, TimeUnit.MILLISECONDS)) {
            LOG.info("Successfully waited for running task to terminate");
        } else {
            LOG.warn("Running task did not terminate in time, forcing termination");
            executorService.shutdownNow();
        }
    } catch (InterruptedException e) {
        LOG.error("Interrupted while waiting for running task to terminate", e);
        executorService.shutdownNow();
    }
}
```

**Comment by engechas** [comment]
**Otel Trace Raw Processor**
I am not sure what a good solution here would be. The condition for flushing partial data should be `isShuttingDown && buffer.isEmpty()`, but the Processor has no knowledge of the buffer size. The [ProcessWorker will send an empty record set](https://github.com/opensearch-project/data-prepper/blob/e614f061660da576565d834130062ed864fe2ac0/data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java#L60-L63) to the Otel Trace Raw Processor, so a slightly hacky solution could be for the partial flush condition could be `isShuttingDown && records.isEmpty()`

**Comment by engechas** [comment]
**Aggregate Processor**
Flushing a partial aggregation appears that it should have a similar condition to the Otel Trace Raw Processor, where the final iteration of ProcessorWorker's `run()` method triggers the flush. The same challenge of determining when the final call to `doExecute` is exists. `isShuttingDown && records.isEmpty()` could be a solution here as well.

**Comment by engechas** [comment]
**Service Map Stateful Processor**
Same characteristics here as the Aggregate and Otel Raw Trace Processors. It seems that once a solution is identified, it should be common across all of the stateful processors.

**Comment by engechas** [comment]
Another potential area where data may be lost is in the event of a Pipeline sink (PipelineConnector) being shutdown. The `stop` method is called before the data has been flushed through the pipeline, which would cause a runtime exception instead of allowing the final data to flow to the next pipeline: https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java#L55

**Comment by graytaylor0** [comment]
> **Otel Trace Raw Processor** I am not sure what a good solution here would be. The condition for flushing partial data should be `isShuttingDown && buffer.isEmpty()`, but the Processor has no knowledge of the buffer size. The [ProcessWorker will send an empty record set](https://github.com/opensearch-project/data-prepper/blob/e614f061660da576565d834130062ed864fe2ac0/data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java#L60-L63) to the Otel Trace Raw Processor, so a slightly hacky solution could be for the partial flush condition could be `isShuttingDown && records.isEmpty()`
> 
> I am not sure if the proposed solution is viable with the `PeerForwarder`

I feel like the real issue here is that `prepareForShutdown` getting called does not mean that the buffer is empty. Is there any way we can change the shutdown flow to

```
1. Shutdown source
2. Wait until buffer is empty
3. Call `prepareForShutdown` on processors (this indicates that the buffer is empty and everything should be flushed)
4. `shutdown` is called and must wait on the processor to flush data
```

**Comment by engechas** [comment]
I think we could push the `prepareForShutdown` call [here](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/Pipeline.java#L189) into the ProcessWorker class's `run` method, something like
```
if (pipeline.isStopRequested() && readBuffer.isEmpty()) {
  processors.forEach(Processor::prepareForShutdown);
}
```

That seems like a good solution to ensure it occurs on the final run of the buffer draining. My only concern is that data could continue to come in through the PeerForwarder as the PeerForwardingProcessorDecorator unions the data sets as part of [Processor.execute](https://github.com/opensearch-project/data-prepper/blob/a452485efa2300edcccd7dcb64df2dc7d5a1247e/data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwardingProcessorDecorator.java#L49). I am not sure if we have an authoritative way to ensure no further data will be received from a peer. Probably need input from @asifsmohammed or @dlvenable here.

**Comment by dlvenable** [comment]
I agree that letting the Buffer drain before calling `prepareForShutdown` could be a good approach. Are there any use-cases which would be counter to this approach? 

The peer-forwarder is a bit of a problem though. If we stop the peer forwarder server too early, then other nodes which are shutting down will not be able to forward events. But, by leaving it open, it is difficult to gauge when all the events have been forwarded and it is safe to shutdown. The peer-forwarder could report is "ready for shutdown" based on the buffer being empty and some configurable delay for waiting for other nodes to send events.

**Comment by engechas** [comment]
> Are there any use-cases which would be counter to this approach?

Not at present. The `prepareForShutdown` method is a no-op for all but the stateful processors. None of the stateful processors required `prepareForShutdown` be called before the final iteration. I would argue a future use case that does want indication that a shutdown is occurring before the buffer is empty should utilize a separate method.

> The peer-forwarder could report is "ready for shutdown" based on the buffer being empty and some configurable delay for waiting for other nodes to send events.

This is a good solution. Ideally we would have a definitive method to determine whether all of the peer forwarder buffers are empty, but for now a timeout should suffice. 

The PeerForwarder interface will need to expose a new method that returns its buffer size. With that, I propose that the `PeerForwarderProcessDecorator`'s `isReadyForShutdown` method be modified to:
```
private long shutdownTime = 0L;
private long shutdownTimeout; // Configurable
...

@Override
public boolean isReadyForShutdown() {
    final boolean isEligibleForShutdown = innerProcessor.isReadyForShutdown() && peerForwarder.isBufferEmpty();
    if (isEligibleForShutdown) {
        final long currentTime = System.currentTimeMillis();

        // Set timeout 
        if (shutdownTime == 0L) {
            shutdownTime = currentTime + shutdownTimeout;
            return false;
        }
        
        return currentTime > shutdownTime;
    }

    return false;
}
```

**Comment by engechas** [comment]
Slight addendum to the above to facilitate calling `prepareForShutdown` before `isReadyForShutdown`

The flow for shutting down in the ProcessorWorker should have 4 steps
1. Loop until `pipeline.isStopRequested() && readBuffer.isEmpty()`
2. Loop until `peerForwarderShutdownTimeout` expires
3. Call `prepareForShutdown` on Processors
4. Loop until all processors' `isReadyForShutdown` return true

The con here is that the peer forwarder's buffer could be non-empty within 1 iteration after `prepareForShutdown` is called which brings the same issues detailed in the initial post. I don't see a way around that without an authoritative method of ensuring the peer forwarder has finished forwarding/receiving all data before step 3.
