### ISSUE TITLE
Update tests and examples after 2.0 Docker image release

### ISSUE THREAD

**Issue by oeyh** [opensearch-project/data-prepper#1805]
There are a few places where Data Prepper image with `latest` tag are pulled for e2e test and demo. This will likely break after 2.0 release and will need an update.

**Comment by dlvenable** [comment]
Data Prepper now supports major tags such as `1`, `2`. These point to the latest version in a major version series. I'd like to suggest that our examples make use of these tags. I think this provides a few benefits.
1. Our examples will not break when a major version is released
2. We will know what version of Data Prepper any given sample is using. 

The downside is that we will need to update these version numbers after major version releases. But, I see this as a relatively small problem. If there are no breaking changes for any given sample, it is quite trivial. If there are breaking changes, we'd still have to change the configuration regardless of using `latest` or the major version tag.

**Comment by oeyh** [comment]
@dlvenable This has been closed via https://github.com/opensearch-project/data-prepper/pull/2019
