### ISSUE TITLE
[BUG] Unable to shutdown Data Prepper Docker with Ctrl+C

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1816]
**Describe the bug**

When running Data Prepper via Docker, I am unable to shut it down using Ctrl+C.

**To Reproduce**

1) Build Data Prepper Docker locally

2) Create a simple pipeline:

```
simple-test-pipeline:
  workers: 2
  delay: "5000"
  source:
    random:
  sink:
    - stdout:
```

3) Run Data Prepper:

```
docker run -p 4900:4900 \
  -v ${PWD}/simple-test/pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml \
  opensearch-data-prepper:2.0.0-SNAPSHOT
```

4) Try to stop with Ctrl+C

**Expected behavior**

I expect Data Prepper to shut down. However, it does not.

If I run with the latest released version, it does shut down:

```
docker run -p 4900:4900 \
  -v ${PWD}/simple-test/pipelines.yaml:/usr/share/data-prepper/pipelines.yaml \
  opensearchproject/data-prepper:1
```

**Environment (please complete the following information):**
 - OS: macOS 12.5
 - Docker Desktop 4.9.0

**Additional context**

Originally reported in the forums: https://forum.opensearch.org/t/latest-data-prepper-not-working/11055

**Comment by oeyh** [comment]
PR #1822 didn't actually fix the issue. I didn't realize that during testing I was running `docker run` with `-it` options, in which case a "Ctrl + c" would shut down the container. Without `-it` options, the issue is still there. Reopen for more investigation.
