### ISSUE TITLE
Reserve pipeline names

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1820]
Reserve the following names by not allowing them in pipelines: `core`, `data-prepper`

**Comment by asifsmohammed** [comment]
It also includes `dataPrepper`. https://github.com/opensearch-project/data-prepper/blob/5344cd32b2b84c10820679cdd8b66972f25fb60e/data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/PipelineConfigurationValidator.java#L29
