### ISSUE TITLE
Bump jackson and snakeyaml dependencies

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/data-prepper#1839]
**Is your feature request related to a problem? Please describe.**
Core has bumped jackson and snakeyaml dependencies [here](https://github.com/opensearch-project/OpenSearch/pull/4556) to `2.13.4` and `1.32` respectively for versions 2.x, 2.3 , 2.2 , 2.1 , 2.0, 1.3 and 1.x. Plugin and client teams should do the same to align with core.

**Describe the solution you'd like**

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by dlvenable** [comment]
We can update to have at least these versions. But, Data Prepper does not run in the same JVM as OpenSearch. So we will not aim to have an exact correspondence.
