### ISSUE TITLE
Correct copyright notices to reflect Copyright OpenSearch Contributors

### ISSUE THREAD

**Issue by dblock** [opensearch-project/data-prepper#189]
Coming from https://github.com/opensearch-project/.github/issues/21.

The correct copyright for open-source projects in opensearch-project is "Copyright OpenSearch Contributors". Please correct any places that say otherwise, especially where it says copyright Amazon. Make sure NOTICE.txt and README match. See https://github.com/opensearch-project/.github/pull/24 for an example.

**Comment by AMoo-Miki** [comment]
The correct header for [this file](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/AwsRequestSigningApacheInterceptor.java) is:

```
/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */
```

Files like [this one](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/sink/SinkFactory.java) that have no other attributions should also use the short version above.

For files that contain attribution to an external project, place this long version above those of the external project(s).

```
/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
```

**Comment by dlvenable** [comment]
Data Prepper Core and Data Prepper API updated in #569
