### ISSUE TITLE
Processor to map values to alternate values

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1914]
**Is your feature request related to a problem? Please describe.**

Some values, such as codes, can be assigned alternate meaning. I'd like to map one value to another.

HTTP status codes are a classic example. I might want to map fields with a value of `200` to `OK` and fields with a value of `404` to `Not Found`.

**Describe the solution you'd like**

Create a new processor which can map values. It should take the following.

* A source key
* A destination key
* A map of values from the source to values to set in the destination.

For example:

```
processor:
  map_value:
    source_key: /status_code
    destination_key: /status
    map:
      200: OK
      404: Not Found
```

I'd like a better name than `map_value`.

Another interesting possibility would be supporting ranges for numbers.

Some examples:

```
processor:
  map_value:
    source_key: /status_code
    destination_key: /status
    range:
      200-399: Success
      400-499: Client Error
      500-599: Server Error
```

And perhaps comma-delimited values:

```
processor:
  map_value:
    source_key: /status_code
    destination_key: /status
    range:
      200,201: Success
      401,403: Authentication
      500-599: Server Error
```

**Comment by vishalboin** [comment]
I have few questions regarding the requirement here. Does yaml support ranges and comma separated values as keys? Can we have 200-250 or 200,201 as key? Do you want separate map, range keys? Can we have only one key map, which can make the configuration simpler?

**Comment by vishalboin** [comment]
@dlvenable I have few questions regarding the requirement here. 

- Does yaml support ranges and comma separated values as keys? Can we have `200-250` or `200,201` as keys? 
- Do you want separate `map`, `range` keys? I think having only one key `map` can make the configuration simpler. 
   Something like:
   ```
   processor:
   map_value:
    source_key: /status_code
    destination_key: /status
    map:
      200: Success
      401,403: Authentication
      500-599: Server Error
   ```

**Comment by dlvenable** [comment]
@vishalboin , Thanks for the feedback and questions!

> Does yaml support ranges and comma separated values as keys? Can we have 200-250 or 200,201 as keys?

Technically, these ranges and keys will be strings. So to the YAML, they will be values like `"200-250"` and `"200,201"`. This processor would need to parse these strings to determine if it is a range or list.

> Do you want separate map, range keys? I think having only one key map can make the configuration simpler.

I like this idea. This could be simpler like you point out with that excellent example.

**Comment by vishalboin** [comment]
@dlvenable , Thanks for the clarification. I have few more questions regarding the plugin functionality
1) Should we handle overlapping values when dealing with numbers? For example consider the following config:
```
  processor:
    - map_value:
        source: code
        destination: test
        map:
          "120,220" : msg1
          "120-220" : msg2
          "120" : msg3
```
How do you think we should handle if we are looking for `120`. Should we throw an error if  such configuration is given or should we try to match the first key, which, in this case would be `"120,220"`.

2) Currently we want to handle individual keys like `120`, or range `120-220` or comma delimited values `120,220`. To give more robustness do you think we should support regular expressions? For example, if we want to have range `120-220` we can give ```"^(1[2-9][0-9]|2[0-1][0-9]|220)$" : msg1 ```  and `120,220` as ```"^(120|220)$" : msg2```. We can have an option to enable such expressions like `regex : true`.

**Comment by kkondaka** [comment]
Let's wait for @dlvenable to comment but I feel supporting regular expression would be too complex with very little value. Regarding the YAML configuration itself, @dlvenable it would be great if you provide the final config you have in mind. Do you mean something like this?
```
processor:
    - map_value:
        source: code
        destination: test
        map: ["200,201" : msg1, "202-220": msg2, "221": msg3]
```
Also, It is my opinion that the range of numbers should be mutually exclusive - ie - for example, 200 cannot be present in more than one mapping. We can support the ability to support a number in multiple mapping with some order of preference but it could get confusing

**Comment by kkondaka** [comment]
Also look at this - https://www.elastic.co/guide/en/logstash/current/plugins-filters-translate.html - while designing/implementing this feature.

**Comment by dlvenable** [comment]
> Also, It is my opinion that the range of numbers should be mutually exclusive - ie - for example, 200 cannot be present in more than one mapping. We can support the ability to support a number in multiple mapping with some order of preference but it could get confusing

I agree with this. I think this should give users a very clear way to map values without ambiguity. This plugin can verify the ranges and then fail fast if there is overlap.

For a final configuration, I think it would be ideal if we could do this:

```
  processor:
    - map_value:
        map:
          120,220 : msg1
          120-220 : msg2
          120 : msg3
```

I'm not sure if YAML will accept this or not. If it does, then this is great. If not, we have to wrap in strings similar to what what @vishalboin had.

```
  processor:
    - map_value:
        map:
          "120,220" : msg1
          "120-220" : msg2
          "120" : msg3
```

> We can have an option to enable such expressions like regex : true.

I also am not sure this is really providing much value in this processor. I think the primary use-case is to handle things like status codes, error codes and map them into some other type of value - often more human readable.

**Comment by oeyh** [comment]
Resolved via translate processor.
