### ISSUE TITLE
[question] dataprepper buffer

### ISSUE THREAD

**Issue by Lmaquaire92** [opensearch-project/data-prepper#1931]
Hello,

what are the default value of buffer_size and batch_size settings  if bounded_blocking section is omit.

thanks

**Comment by chenqi0805** [comment]
@Lmaquaire92 Thanks for your interest! You could refer to bounded_blocking in opensearch doc: https://opensearch.org/docs/2.3/clients/data-prepper/data-prepper-reference/ . The default buffer_size is 512 and batch_size is 8.

**Comment by dlvenable** [comment]
These values are accurate only for 1.x. We updated these for 2.x in #1906.

buffer_size = 12,800
batch_size = 200

**Comment by dlvenable** [comment]
I created #1983 to track correcting this documentation.
