### ISSUE TITLE
Test against multiple OTel version

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1963]
**Is your feature request related to a problem? Please describe.**

Updating OTel versions may break existing features. Data Prepper's end-to-end tests should be able to test against clients using different OTel versions.

**Describe the solution you'd like**

Allow the end-to-end tests to run with a configurable OTel client version. Make the GitHub actions run a matrix which includes the version used in `2.0` and the version that we are updating to in #1335.

It can be provided as a Gradle argument similar to how we pass in a Java argument.

The following shows how Data Prepper currently tests multiple Java clients in the end-to-end tests.

https://github.com/opensearch-project/data-prepper/blob/43b7d33c28cb8572a92c397d59e90a3d9aba6ebb/.github/workflows/data-prepper-log-analytics-basic-grok-e2e-tests.yml#L30

**Describe alternatives you've considered (Optional)**

Update the OTel version in Data Prepper only at major versions. But, this will hinder progress.

**Additional context**

The work done in #1335 is updating the OTel version. It is passing, but it uses the updated OTel version as the same OTel version in Data Prepper. It is possible that this is a breaking change and it needs to be verified.

**Comment by kkondaka** [comment]
I can work on this.
