### ISSUE TITLE
OpenSearch source plugin

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1985]
**Is your feature request related to a problem? Please describe.**

Some users have looked for a way to migrate data from one OpenSearch cluster to another. One of the missing components here would be the ability to retrieve data from OpenSearch. Other users have expressed a need to transform data from OpenSearch clusters.

**Describe the solution you'd like**

Include an OpenSearch source plugin for Data Prepper. It will need some of the following configurations.

* Connection configurations similar to the `opensearch` sink.
* Source index or indices. This should also support dynamic indices based on date.
* Possibly query options to filter down the data. If not specified, all data in the index would be used.
* Schedule configurations for reading data.

**Additional context**

This should be similar to the `logstash-input-opensearch-plugin` provided in the OpenSearch project.

https://opensearch.org/blog/community/2022/05/introducing-logstash-input-opensearch-plugin-for-opensearch/
https://github.com/opensearch-project/logstash-input-opensearch

**Comment by cmanning09** [comment]
This issue should not be closed.

**Comment by cmanning09** [comment]
![OpenSearchSource](https://github.com/opensearch-project/data-prepper/assets/4857376/0de0bfa0-d777-4c6d-a35d-dc2cc8576764)

High level proposal for class design for this plugin

**Comment by cmanning09** [comment]
Latest PR: https://github.com/opensearch-project/data-prepper/pull/2806 from @graytaylor0
