### ISSUE TITLE
Support for metadata and types in expressions

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1998]
**Is your feature request related to a problem? Please describe.**

The Data Prepper event model has support for [metadata](https://github.com/opensearch-project/data-prepper/blob/db8ca416b7467e45a599c7681ce72b607fc6fc9e/data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/EventMetadata.java#L15-L36) which includes type information.

Data Prepper expression syntax allows for accessing data using JSON Pointer syntax. For example, `/status_code`. However, there is no mechanism to access Event Metadata.

Some pipeline authors would like to perform pipeline routing based on event type. Some others might want to filter based on tags (#629).

**Describe the solution you'd like**

Design and implement a syntax that allows for accessing any EventMetadata.

**Additional context**

The discussion around supporting Event tags offers a proposal for `getTags()` in [this comment](https://github.com/opensearch-project/data-prepper/issues/629#issuecomment-1190938897).

**Comment by kkondaka** [comment]
Working on adding `getMetadata()` function to DataPrepper Expressions which looks up a key in the event's metadata attributes. For event type, `getEventType()` function can be added in future.
Examples - `getMetadata("key1")` `getMetadata("key1/key2"), `getMetadata("key1/key2/key3")` when "/" present, the lookup is done nested way. This is similar to the way key lookup is done in events. The keys could start with "/" (as in `getMetadata("/key1")` `getMetadata("/key1/key2"), `getMetadata("/key1/key2/key3")` ) and they are treated same as the keys without preceding "/"

**Comment by kkondaka** [comment]
Fixed by PR #2690
