### ISSUE TITLE
Add backwards compatibility tests for automation

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/data-prepper#200]
Add backwards compatibility tests for the plugin to automate end-to-end upgrade paths for faster releases. Developer documentation for implementing bwc tests and hooking them to CI: https://github.com/opensearch-project/opensearch-plugins/blob/main/TESTING.md#backwards-compatibility-testing

**Comment by laneholloway** [comment]
@VachaShah we are not a plugin for Opensearch, can you please explain more clearly what you are expecting?

**Comment by VachaShah** [comment]
Hi @laneholloway, this issue is for adding backwards compatibility tests, we started it out for plugins and they can use the OpenSearch infrastructure to write bwc tests. For data-prepper, if the same infrastructure does not apply, the bwc tests can be written according to your use cases.

**Comment by laneholloway** [comment]
You can view it [here](https://github.com/opensearch-project/data-prepper/tree/main/.github/workflows) each workflow iterates through the OpenSearch versions.

**Comment by nknize** [comment]
> each workflow iterates through the OpenSearch versions.

Sorry if I'm dense; what does this mean? It iteratively tests it on all the versions? Or does it spin up an "old cluster", index data, spin up a "new cluster", and test for BWC support?

**Comment by laneholloway** [comment]
We iteratively test each version of OpenSearch against Data Prepper on each PR.
