### ISSUE TITLE
Data Prepper - Metrics - HTTP Source

### ISSUE THREAD

**Issue by fkirwin** [opensearch-project/data-prepper#2139]
**Is your feature request related to a problem? Please describe.**
This feature isn't quite a problem, but I would like to see OTLP/HTTP data source implemented on https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins/otel-metrics-source.  Currently it appears as though only GRPC is supported.

**Describe the solution you'd like**
I would like to see the OTLP/HTTP source implemented for metrics, just like it is for the traces source.

**Describe alternatives you've considered (Optional)**
The alternative is to switch my pipeline to all GRPC.  That would work, but requires more effort.

**Additional context**
I am guessing this is in the works, but I am curious when we could expect a push for this functionality?

**Comment by dlvenable** [comment]
@fkirwin ,

I understand that you want to send HTTP messages to the `otel-metrics-source` instead of using gRPC. Correct?

There is an existing option to support `unframed_requests` in the `otel-metrics-source`. This should provide that functionality. Did you try this? If so, what behavior did you have?

**Comment by fkirwin** [comment]
@dlvenable 
Thanks for your response!  I can confirm that the Data Prepper is working using the settings outlined here.  Here are the details about my test if anyone is curious.  I am sending the data via the OTEL collector.

Source:
OTEL-HTTP
otlphttp/dataprepper:
   metrics_endpoint: http://<localdocker>:21891/opentelemetry.proto.collector.metrics.v1.MetricsService/Export
   compression: none
   headers:
     Content-Type: application/protobuf
     
For the dataprepper I used the unframed_requests set to true inside the otel-metrics source.

**Comment by dlvenable** [comment]
@fkirwin , Thank you for getting back to us. To clarify, you were able to configure this setting and get your metrics to flow into Data Prepper, right? Can we close this issue?

**Comment by fkirwin** [comment]
Yes, everything working now.

**Comment by dlvenable** [comment]
Closing this issue since the functionality already exists.
