### ISSUE TITLE
Improve ReceiveBuffer Performance

### ISSUE THREAD

**Issue by asuresh8** [opensearch-project/data-prepper#2142]
Looking at the ReceiveBuffer code, there are a few optimization that can be done:
1. Better use of semaphore. The semaphore should be released when reading from the queue instead of in the checkpointing stage. It's not clear to me that the checkpointing stage actually does any checkpointing.
2. The read code is written inefficiently. The read method should not take in a timeout. If there is data to read, then read, otherwise return and continue. The 3 second wait doesn't yield the CPU and takes up cycles that could be used by another processor in the pipeline. Additionally, there is no need to poll and then drainTo. Just running drainTo achieves the same result without need to acquire the read lock twice.

**Comment by dlvenable** [comment]
Regarding item 1, the semaphore reserves the space in the buffer so that new items will not populate until the data has been sent to the sink.

Item 2 was resolved in #2189 and #2246.
