### ISSUE TITLE
Add missing metrics for Opensearch Sink

### ISSUE THREAD

**Issue by dinujoh** [opensearch-project/data-prepper#2168]
**Is your feature request related to a problem? Please describe.**
The Opensearch sink is missing instrumentation for Opensearch client/server exception. It is also missing metrics when the request is retried. The Opensearch sink only records metrics for error in bulk [operation response](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java#L156-L169).  It would be nice to have metrics for Opensearch Client/Server exception apart from Api exception.

Code reference:

* https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java#L92-L106
* https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java#L134

**Describe the solution you'd like**
Add instrumentation to Opensearch Client/Server exception.

**Comment by kkondaka** [comment]
I can take a look at this

**Comment by dlvenable** [comment]
@dinujoh , I want to clarify the request here.

You want to have new metrics which count the errors by type?

So perhaps metrics like these?

* `bulkRequestTimeout` - count
* `bulkRequestServerError` - count
* `bulkRequestRetryableError` - count

Thoughts?

**Comment by dinujoh** [comment]
> 
> You want to have new metrics which count the errors by type?
> 
Yes, this will be helpful. OpenSearch Sink is configured with exponential retry with no bound to max retries. Visibility into why the retry is failing with error type will be helpful.

> So perhaps metrics like these?
> 
> * `bulkRequestTimeout` - count
> * `bulkRequestServerError` - count
> * `bulkRequestRetryableError` - count
> 
> Thoughts?

Yes, these metrics makes sense. Looks like `bulkRequestRetryableError` will be aggregate metric when request is retried. `bulkRequestTimeout` and `bulkRequestServerError` are specific exception for retry. If there are additional exception handling for retry exception, we should metric them as well.
