### ISSUE TITLE
Support Amazon Opensearch Serverless Sink

### ISSUE THREAD

**Issue by dinujoh** [opensearch-project/data-prepper#2169]
**Is your feature request related to a problem? Please describe.**
It would be nice to have support for [Amazon Opensearch Serverless](https://aws.amazon.com/opensearch-service/features/serverless/) Sink. Amazon Opensearch supports preview for Serverless. As a developer, you can use OpenSearch Serverless to run petabyte-scale workloads without configuring, managing, and scaling OpenSearch clusters.  

**Describe the solution you'd like**
New plugin to support Amazon Opensearch Serverless as Sink. 

**Tasks**

- [ ] #1881
- [ ] #2281

**Comment by dlvenable** [comment]
I'm not sure we want a new sink here. We could make this a configuration on the existing `opensearch` sink.

One possible approach could be based on the solution for #877. In addition to `opensearch` and `opendistro`, Data Prepper could have an `aws_serverless` option here.

Or maybe this should be a completely different parameter entirely. Either way, I think we can make this work in the existing sink plugin.

Is there a particular reason you propose a different sink plugin?
