### ISSUE TITLE
Validate S3 URI in OpenSearch options which support S3 files

### ISSUE THREAD

**Issue by asifsmohammed** [opensearch-project/data-prepper#2177]
**Is your feature request related to a problem? Please describe.**
With the recent changes made to OpenSearch sink as part of https://github.com/opensearch-project/data-prepper/issues/2120 to support loading index mapping and ISM policy file from S3 we only check if the S3 URI starts with a prefix of `s3://`

**Describe the solution you'd like**
We should add a robust way to check the entire S3 URI instead of just the prefix to ensure that URI is valid S3 URI.

**Comment by dlvenable** [comment]
Is there an existing parser in the AWS Java SDK? Or another recommendation from the S3 team?
