### ISSUE TITLE
Sensitive argument masking in Data Prepper log format.

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#2187]
**Is your feature request related to a problem? Please describe.**
We want to provide the ability to mask sensitive data based off markers used in log event. e.g.

LOG.error(SENSITIVE, "log message with anchor: {}", "sensitive data");

will be logged as

```
log message with anchor: ******
```

**Describe the solution you'd like**
We will implement a `SensitiveArgumentMaskingConverter` in package `org.opensearch.dataprepper.logging` that extends `LogEventPatternConverter` in formatting the log message string and applies to the convertKey called mask:
```
@Plugin(name = "sensitiveArgumentMaskingConverter", category = PatternConverter.CATEGORY)
@ConverterKeys({"mask"})
public class SensitiveArgumentMaskingConverter extends LogEventPatternConverter
```
Then in the log4j2.xml, one can apply masking through including `org.opensearch.dataprepper.logging` into configuration package and apply %mask. e.g.:

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration packages="org.opensearch.dataprepper.logging">
    <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{ISO8601} [%t] %-5p %40C - %mask%n"/>
        </Console>
    </Appenders>
    <Loggers>
        <Root level="info">
            <AppenderRef ref="Console"/>
        </Root>
    </Loggers>
</Configuration>
```

**Describe alternatives you've considered (Optional)**
1. hard removal of sensitive argument. This has the downside of non-user friendly in debugging.
2. repeat the same log event with independent marker. e.g.
```
LOG.error(SENSITIVE, "log message: {}", "sensitive data");
LOG.error(NON_SENSITIVE, "log message.");
```
while this gives user the option to apply marker, it might not persist well for future development efforts as developer needs to repeat every potentially sensitive log message twice.

**Additional context**

**Comment by dlvenable** [comment]
Completed by #2188
