### ISSUE TITLE
Support multi-line logs in the grok processor

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#2204]
**Is your feature request related to a problem? Please describe.**
The library used for the grok processor (https://github.com/thekrakken/java-grok) only supports single line logs, and as a user I would like to grok my multi-line logs

**Describe the solution you'd like**
Built-in support for multi-line grokking within the grok processor. This could include an additional configuration option, such as `is_multi_line` (defaults to false), to indicate that the logs are multi-line. If this option were set to true, then the grok processor would replace all newlines in patterns that are supplied in `match` or `pattern_definitions` with a special character (or potentially a unique hash?), such as `|`, and the grok processor would also replace all newlines in logs with this special character before matching against them.

The thought process behind explicitly stating `is_multi_line` as a configuration option would be to avoid the unnecessary performance impact that could occur from replacing all the newlines in each log. It is worth noting that single line logs would still work as intended while `is_multi_line` is set to `true`, since the replacement of newlines would be a no-op.

 One additional complication that arises is that we don't want to modify the user's original logs, so we would need to replace the special characters with newlines again after grokking. This would be an issue if the user's logs also contained the special character, so the easy way to solve this would be to create a copy of the logs before the newlines are replaced, rather than having to track all the replacements that occurred to undo them. Another option to solve this problem would be to reserve the special character, but that is not ideal since there is always the chance that a user's logs would contain this special character, no matter how rare it would be.

The easiest solution would be to just remove newlines from the logs and patterns, but this would not keep things fully consistent since users do want to match based on newlines. 

**Describe alternatives you've considered (Optional)**
Adding a `substitute_string` processor before the `grok` processor to replace newlines with a different character, and then including this character in the grok patterns supplied for grok.

**Comment by kkondaka** [comment]
Do we need this? See this thread - https://stackoverflow.com/questions/26474873/how-do-i-match-a-newline-in-grok-logstash/26475308#26475308
