### ISSUE TITLE
Support metric tags based on metric name regex

### ISSUE THREAD

**Issue by asifsmohammed** [opensearch-project/data-prepper#2229]
**Is your feature request related to a problem? Please describe.**
Data Prepper supports metricTags where you can define a map of key, value pairs to be added to all metrics. There is no way to add tags based on a regex or a prefix of metric. Users should have more control over the metric tags.

**Describe the solution you'd like**
Data Prepper user can configure `metricsTags` as a list of regex with map of tags to apply to the metrics which match to the regex. The regex patterns will be checked in order till a match occurs and a maximum of one regex will be matched. With this user can add tags to specific set of metrics instead of all metrics.

Data Prepper plugin metrics are prefixed with `<pipeline-name>.<plugin-id>`.  So users can use the prefixes and to set tags for any specific prefix.
```
metricTagFilters:
  - pattern: "log-pipeline.*"
    tags:
      key1: value1
  # adds following tags to all metrics which didn't match any previous regex
  - pattern: ".*"
    tags:
      key2: value2
```
This solution can be a breaking change. Instead, we can create a new option (`metricTagsFilter`) instead of replacing `metricTags` and iterate over all regex pattern's in `metricTagsFilter` and if nothing matches, we can apply the `metricTags` at the end. And `metricTags` can be removed in next major version.

**Describe alternatives you've considered (Optional)**
Alternatively, we can add an option metricTagFilters where you can specify the metrics to which tags shouldn't be applied.
```
metricTags: 
  key1: value1
metricTagFilters: ["core.peerforwarder"]
```
In the above example tags will be applied to all metrics other than metrics starting with `core.peerforwarder`

This allows users to have more control over the tags. Here are some of the use cases
1. Allows customers with connected pipelines tag metrics by pipeline
2. Users can add separate tags to Peer Forwarder, plugin metrics
3. This will allows users to add tags to AWS SDK metrics mentioned here https://github.com/opensearch-project/data-prepper/issues/2087

**Comment by dlvenable** [comment]
The proposal for `metricsTags` would give users quite a bit of flexibility. With the `metricsTagFilter` we'd only be to remove the common tags. Plus, what if we have a subset of `metricTags` which we want to have filtered?

The approach does have to be non-breaking. So, the first proposal probably needs a new name. Maybe something like `metricTagRules`?

**Comment by dlvenable** [comment]
Another thought is about the pattern matching.

This proposal is to use Java regex patterns. These are powerful, but a little complex.

For example, the example you gave - `"log-pipeline.*"` - matches `log-pipeline2.opensearch.bulkBadRequestErrors`. That might not be what a user expects.

Might it be better to use a modified Ant-path pattern matcher? Metric names follow a fairly straight-forward pattern making them suitable for a simpler syntax. Plus, `.` is used throughout metric names and is a Java regex pattern character.

Here is a short Javadoc with some examples and explanation.

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html

For the example above with `log-pipeline.*`, it would need to be replaced by `log-pipeline.**`, but it would match what you expect.

Say we have an Ant-path style matcher like this: `entry-pipeline.**.*Errors`. It would get all metrics from the entry-pipeline that end in Error.

Also, I suppose we could support both (`regex:` and `ant_pattern:`) options.

**Comment by asifsmohammed** [comment]
> The approach does have to be non-breaking. So, the first proposal probably needs a new name. Maybe something like metricTagRules?

This will be a non-breaking change. `metricTagFilters` is the new option.

> Might it be better to use a modified Ant-path pattern matcher?

Yes, I think this suits the use-case better. 

> Also, I suppose we could support both (regex: and ant_pattern:) options.

I think, using both might introduce a confusing behavior. We should just stick with one for now (Ant path)
