### ISSUE TITLE
Change the path prefix for OTel endpoints

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#2257]
**Is your feature request related to a problem? Please describe.**

When running Data Prepper with unframed requests, an OTel source has a predefined path.

For example, with traces, the path is the following:

```
opentelemetry.proto.collector.trace.v1.TraceService/Export
```

**Describe the solution you'd like**

I'd like to be able to set either the path or the path prefix.

For example, I may wish to write to:

```
http://localhost:21890/service-a/opentelemetry.proto.collector.trace.v1.TraceService/Export
```

**Describe alternatives you've considered (Optional)**

This could be accomplished either by changing the whole path or the path prefix.

Changing the whole path:

```
entry-pipeline:
  source:
    otel_trace_source:
      path: service-a/traces
```

Would result in the following path:

```
http://localhost:21890/service-a/traces
```

Whereas changing the path prefix would be different. Given the following configuration:

```
entry-pipeline:
  source:
    otel_trace_source:
      path_prefix: service-a
```

The final path would be:

```
http://localhost:21890/service-a/opentelemetry.proto.collector.trace.v1.TraceService/Export
```

**Additional context**

The OTel HTTP Exporter does support modifying the path as noted in the [reference documentation](https://github.com/open-telemetry/opentelemetry-collector/blob/e2a6cd7a18ac74a9cf9a3d252cb8efd4726c1727/exporter/otlphttpexporter/README.md). It offers configurations for `traces_endpoint`, `metrics_endpoint`, and `logs_endpoint`.

However, this might not work with gRPC requests. The [documentation](https://github.com/open-telemetry/opentelemetry-collector/blob/e2a6cd7a18ac74a9cf9a3d252cb8efd4726c1727/exporter/otlpexporter/README.md) shows no such options to configure the service name.

**Comment by asifsmohammed** [comment]
OTel paths are of the format `serviceName/Method`, so path for OTel Trace source in Data Prepper is following
`/opentelemetry.proto.collector.trace.v1.TraceService/Export`

GrpcServiceBuilder allows it be modified to `customPath/Method` so resulting path will be
`customPath/Export`. We need to change the whole path which is the alternative solution proposed.

**Comment by dlvenable** [comment]
Thanks for the explanation here!

> We need to change the whole path which is the alternative solution proposed.

I'm not sure I follow this statement. Based on the rest of your explanation, I think we could support changing the prefix part only. Does Armeria/gRPC allow changing the whole path?

**Comment by asifsmohammed** [comment]
> Does Armeria/gRPC allow changing the whole path?

Once we use custom path then it will replace the default service name path which is `opentelemetry.proto.collector.trace.v1.TraceService` with custom path.
