### ISSUE TITLE
Support a version property in pipeline YAML configurations

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#2263]
## Problem

Pipeline configurations may change between major versions of Data Prepper. It can be useful to know what version of Data Prepper a given pipeline configuration was written to support and tested against.

## Proposal

Provide a pipeline definition version property in the pipeline configuration file. Specifically in the YAML, this would be a new property: `version`.

Example:

```
version: 2
otel-trace-pipeline:
  source:
    otel_trace_source:
  buffer:
  sink:
    ...
raw-pipeline:
  source:
    ..
  sink:
    ...
service-map-pipeline:
  source:
    ...
  sink:
    ...
```

The `version` can support strings in either forms:
* `${major}` (e.g. `2`)
* `${major}.${minor}` (e.g. `2.2`)

As patch versions of Data Prepper only provide bug fixes, there should be no need to include patch versions in the `version`.

Data Prepper would read the pipeline definition version and compare its current version against the definition supplied. Data Prepper will only report an error to users if the pipeline definition version represents a future version of Data Prepper.

If the pipeline definition version is older, Data Prepper will attempt to parse the configuration. It may not succeed if the major version is different and there are breaking changes reflected in the pipeline. Because a pipeline that works on 2.x may still run on 3.x, Data Prepper should at least attempt to parse it.

### Not in scope

Data Prepper could support a mechanism for reading older pipeline definition files. For example Data Prepper 3.x could read and understand breaking changes from 2.x pipelines. This proposal does not include any such attempts at keeping pipeline files operational indefinitely. This may add friction to further development of new features.

### Alternative names

I considered some other names.
* `definition_version` - This might clearly indicate that it is for the pipeline definition, but may be too verbose.
* `pipeline_version` - Even more that `version` this sounds like it is a version of the pipeline itself.
* `pipeline_definition_version` - This is accurate, but possibly too verbose.

### Alternative form

The current syntax of the pipeline YAML is a key-value map of `pipelineName:pipelineBody`. This would change that structure by adding a new key at the top: `version: ${version}`.

An alternative would be to create a modified structure:

```
version:
pipelines:
  entry-pipeline:
    ...
  raw-pipeline:
    ...
  service-map-pipeline:
    ...
```

This would break all existing pipeline YAML files. I do not believe we should take this alternative YAML.

There is the possibility that somebody has a pipeline named `version`. In which case, such a pipeline would fail to run with this change. As this is not highly likely, I suggest that we move forward with supporting existing pipelines which do not use `version` in the name.

## Additional questions

Data Prepper has a core syntax as expressed in [PipelinesDataFlowModel](https://github.com/opensearch-project/data-prepper/blob/c797d5cb85f5b7a02b8ff325846ee12f6be71904/data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/PipelinesDataFlowModel.java). Data Prepper also has a set of built-in plugins. Should the version indicate only the pipeline syntax or also the available plugins for a given version? If the latter, how would we account for extracting plugins out of Data Prepper (see #321).

**Comment by rohankadam284** [comment]
+1

**Comment by cmanning09** [comment]
I like simplifying this to `version`. The context of the file should be enough

**Comment by dlvenable** [comment]
> I like simplifying this to `version`. The context of the file should be enough

Thanks @cmanning09 , I updated the issue to use `version` instead of `definition_version`.

**Comment by cmanning09** [comment]
@dlvenable & @rohankadam284, I am going to make this attribute a double given we only need to support major and minor versions.

Data Prepper does not maintain or track a version with the exception of this gradle property which is only used on building. Any suggestions or thoughts with how we should define the support version in the project? 
https://github.com/opensearch-project/data-prepper/blob/main/gradle.properties

**Comment by dlvenable** [comment]
@cmanning09 , I think using a string may be better. The values `2` and `2.0` may carry different meaning to some extent and this would be lost with a double.

I'd also probably advise creating a model class - `DataPrepperVersion`:

Maybe something like:

```
class DataPrepperVersion {
  public int getMajorVersion();
  public Optional<Integer> getMinorVersion();
}
```

**Comment by dlvenable** [comment]
Also, you can make it `Comparable`. And you might not need to expose the major/minor.

Here is another take:

```
public class DataPrepperVersion implements Comparable<DataPrepperVersion> {
  private int majorVersion;
  private Integer minorVersion;

  public int compareTo(DataPrepperVersion) { ... }

  public static DataPrepperVersion getCurrentVersion();

  public static DataPrepperVersion parse(String version) { ... };
}
```

**Comment by cmanning09** [comment]
Ahh when you say carry different meaning you mean 2 == 2.3 but 2.0 != 2.3. Yes I agree.
