### ISSUE TITLE
[BUG] Jaeger Hotrod demo does not work

### ISSUE THREAD

**Issue by sergey-rsa** [opensearch-project/data-prepper#2273]
**Describe the bug**
data-prepper/examples/jaeger-hotrod does not work
no traces in Kibana
and error in logs
2023/02/14 12:00:26 Post "http://localhost:14268/api/traces": dial tcp 127.0.0.1:14268: connect: connection refused

**To Reproduce**
1. clone repo
2. docker-compose up --build
3. open application in browser, press any button

**Screenshots**
![image](https://user-images.githubusercontent.com/1929607/218732576-598380f7-a452-4404-9ae0-799a4f541d2c.png)

**Environment (please complete the following information):**
 - OS: [linux Mint 21.1]

**Comment by sshivanii** [comment]
Hi @derangeer,

Thanks for reporting this. I was able to reproduce the same error when I ran the `jaeger-hotrod` example as well. We will add this Bug to our tracking board and this issue will be updated with any further updates.
```
jaeger-hotrod-jaeger-hot-rod-1  | 2023/02/21 18:10:03 Post "http://localhost:14268/api/traces": dial tcp 127.0.0.1:14268: connect: connection refused
jaeger-hotrod-jaeger-hot-rod-1  | 2023/02/21 18:10:03 Post "http://localhost:14268/api/traces": dial tcp 127.0.0.1:14268: connect: connection refused
jaeger-hotrod-jaeger-hot-rod-1  | 2023/02/21 18:10:03 Post "http://localhost:14268/api/traces": dial tcp 127.0.0.1:14268: connect: connection refused

```

**Comment by rizwan-balouch** [comment]
i am also facing same, any solution ?

**Comment by omishagupta** [comment]
As mentioned by @fridgepoet, updating the docker image to `1.41.0` worked like charm.

**Comment by beachwood23** [comment]
I am still seeing this issue, although with a slightly different error message. I see a repeating of:

```
data-prepper                    | 2023-11-06T18:30:05,749 [service-map-pipeline-sink-worker-4-thread-1] WARN  org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink - Failed to initialize OpenSearch sink, retrying: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
data-prepper                    | See https://opensearch.org/docs/latest/clients/java-rest-high-level/ for troubleshooting. 
data-prepper                    | 2023-11-06T18:30:05,831 [raw-pipeline-sink-worker-6-thread-1] INFO  org.opensearch.dataprepper.pipeline.Pipeline - Pipeline [raw-pipeline] - sink is not ready for execution, retrying
data-prepper                    | 2023-11-06T18:30:05,831 [raw-pipeline-sink-worker-6-thread-1] INFO  org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink - Initializing OpenSearch sink
data-prepper                    | 2023-11-06T18:30:05,831 [raw-pipeline-sink-worker-6-thread-1] INFO  org.opensearch.dataprepper.plugins.sink.opensearch.ConnectionConfiguration - Using the username provided in the config.
data-prepper                    | 2023-11-06T18:30:05,831 [raw-pipeline-sink-worker-6-thread-1] INFO  org.opensearch.dataprepper.plugins.sink.opensearch.ConnectionConfiguration - Using the cert provided in the config.
data-prepper                    | 2023-11-06T18:30:05,847 [raw-pipeline-sink-worker-6-thread-1] WARN  org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink - Failed to initialize OpenSearch sink, retrying: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
```

**Comment by t1** [comment]
@beachwood23 : that looks like your server uses a certificate that is either self-signed or signed by a CA that is not in your keychain.

**Comment by beachwood23** [comment]
I haven't been able to debug the certificates issue. I am not sure which part is going wrong there. 

I have tried to set this up without using any security at all, and am seeing a different failed port connection:

```
jaeger-hotrod-jaeger-hot-rod-1  | 2023/11/07 22:38:07 traces export: Post "http://localhost:4318/v1/traces": dial tcp 127.0.0.1:4318: connect: connection refused
```

**Comment by fridgepoet** [comment]
I started getting the following recently:
`WARN  org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink - Failed to initialize OpenSearch sink, retrying: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
`

What worked is for me is replacing `image: opensearchproject/opensearch`'s :`latest` to `:2.9.0`
image: opensearchproject/opensearch:2.9.0

The other replacement still seems necessary, too: https://github.com/opensearch-project/data-prepper/issues/2273#issuecomment-1464092972

(@beachwood23 I suspect this was your problem)

**Comment by frodopwns** [comment]
I am getting this connection refused error when trying to use the demo app as well.

**Comment by linghengqian** [comment]
- I noticed this issue while investigating https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8075 . I was surprised that the contents of `root-ca.pem` were actually mounted to a directory on the host, which limited user options and caused a lot of confusion. I've opened #4921 to fix this issue.

**Comment by linghengqian** [comment]
> In the docker-compose you could change the `image:jaegertracing/example-hotrod` ‘s `:latest` to `:1.41.0` which was working for me

- I've opened #4923 to discuss this.
