### ISSUE TITLE
Aiven Kafka connector support

### ISSUE THREAD

**Issue by ashoktelukuntla** [opensearch-project/data-prepper#2293]
**Is your feature request related to a problem? Please describe.**

Data prepper should be able to support events from Aiven Kafka connector

**Describe the solution you'd like**

Add Sigv4 support for Aiven Kafka connector enabling the same to post data to Dataprepper pipelines. I would envision the below sequence

1. Get branch : [Sigv4 Changes](https://github.com/deepdatta/http-connector-for-apache-kafka/tree/sigv4_support)
2. Confirm the HTTP format to configure a Data Prepper pipeline
3. Test against open-source Data Prepper without SigV4; using HTTP source
4. Test against OSI (same pipeline with SigV4)
5. Make any changes to the branch so that it works correctly
6. Create PR in to Aiven

**Additional context**
References: https://github.com/aiven/opensearch-connector-for-apache-kafka
https://github.com/deepdatta/http-connector-for-apache-kafka/tree/sigv4_support
https://github.com/deepdatta/opensearch-connector-for-apache-kafka-sigv4-configurator

**Comment by dlvenable** [comment]
This is not a change for Data Prepper.
