### ISSUE TITLE
[Refactor] XContent from common to core namespace

### ISSUE THREAD

**Issue by nknize** [opensearch-project/data-prepper#2404]
XContent namespace refactor from common -> core is going to be merged to opensearch/2.x which will break the 2.x build.  This issue is for refactoring XContent imports from the `common` to `core` namespace after the core namespace change is merged.

Depends on https://github.com/opensearch-project/OpenSearch/pull/6470

**Comment by nknize** [comment]
https://github.com/opensearch-project/OpenSearch/pull/6470 merged

**Comment by dlvenable** [comment]
Data Prepper is not an OpenSearch plugin and has nothing to do to support this change.
