### ISSUE TITLE
Keyed-list to flattened map processor

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#2410]
**Is your feature request related to a problem? Please describe.**

Some inputs may come in the form of a list of objects where each object has a natural "key" field. Pipeline authors may want to convert this into a map of keys to objects.

**Describe the solution you'd like**

Provide a processor which can perform this conversion. Say I have a Data Prepper event with the following structure.

```
{
  "mylist" : [
    {
      "somekey" : "a",
      "somevalue" : "val-a1",
      "anothervalue" : "val-a2"
    },
    {
      "somekey" : "b",
      "somevalue" : "val-b1",
      "anothervalue" : "val-b2"
    },
    {
      "somekey" : "b",
      "somevalue" : "val-b3",
      "anothervalue" : "val-b4"
    },
    {
      "somekey" : "c",
      "somevalue" : "val-c1",
      "anothervalue" : "val-c2"
    }
  ]
}
```

If I define the following parameters in the processor:
* `key` - "somekey"
* `source` - "mylist"
* `target` - "myobject"

The processor will change the event by removing `mylist` and adding the new `myobject` object. The event will look like the following.

```
{
  "myobject" : {
    "a" : [
      {
        "somekey" : "a",
        "somevalue" : "val-a1",
        "anothervalue" : "val-a2"
      }  
    ],
    "b" : [
      {
        "somekey" : "b",
        "somevalue" : "val-b1",
        "anothervalue" : "val-b2"
      },
      {
        "somekey" : "b",
        "somevalue" : "val-b3",
        "anothervalue" : "val-b4"
      }
    "c" : [
      {
        "somekey" : "c",
        "somevalue" : "val-c1",
        "anothervalue" : "val-c2"
      }  
    ]
  }
}
```

In many cases, we also want to flatten the array for each key. In these situations, we must choose only one object to remain. The processor can offer the choice of either `first` or `last`.

If flattened, the processor will yield:

```
{
  "myobject" : {
    "a" : {
      "somekey" : "a",
      "somevalue" : "val-a1",
      "anothervalue" : "val-a2"
    },
    "b" : {
      "somekey" : "b",
      "somevalue" : "val-b1",
      "anothervalue" : "val-b2"
    }
    "c" : {
      "somekey" : "c",
      "somevalue" : "val-c1",
      "anothervalue" : "val-c2"
    }  
  }
}
```

I propose calling this processor `list_to_map`, but am very open to other ideas.

The following properties may exist on it.

* `source` - The key of the source list
* `target` - The key of the target object
* `key` - The key of the field which will serve as the key in the target object.
* `value_key` - If specified, this will extract the value from the specified key to make the target.
* `flatten` - A boolean value. If set to true, then flatten into one object
* `flattened_element` - Can be either `first` or `last`. Defines which element from the list to choose when multiple exist. Can default to first. 

Here is another sample output if we specify the `value_key` to "somevalue." This will pull up the value from "somevalue" and make it the target value. In this example, we are not flattening the object.

```
{
  "myobject" : {
    "a" : ["val-a1"],
    "b" : ["val-b1", "val-b3"]
    "c" : ["val-c1"]
  }
}
```

And in this example, we do choose to flatten the object.

```
{
  "myobject" : {
    "a" : "val-a1",
    "b" : "val-b1",
    "c" : "val-c1"
  }
}
```

**Comment by oeyh** [comment]
@dlvenable This is quite a generic solution! I see that it covers a lot of potential use cases for extracting a list of objects into a map.

One addition I can think is that the `value_key` can also accept a list if multiple but not all values need to be extracted.
