### ISSUE TITLE
[BUG] Grok Debugger is down

### ISSUE THREAD

**Issue by markkuhn** [opensearch-project/data-prepper#2423]
**Describe the bug**
The [Grok Debugger](https://grokdebug.herokuapp.com/) is down.

**To Reproduce**
1. Go to https://grokdebug.herokuapp.com/

**Expected behavior**
I expect the Grok Debugger to be available to use.

**Screenshots**
Not necessary.

**Environment (please complete the following information):**
Not applicable.

**Comment by chenqi0805** [comment]
Confirmed that the debugger in the grok processor README link is down: https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/grok-processor/README.md#grok-processor. Will replace with a new one.
