### ISSUE TITLE
Ability to combine multiple Event keys into one new Event key

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#2424]
**Is your feature request related to a problem? Please describe.**
As a user of data prepper, I would like the ability to add new Event entries dynamically from existing Event entries. Given the following Event

```
{
   "key_one": "value_one",
   "key_two": "value_two"
}
```

I would like to transform the Event with a new key that combines these values into the following Event

```
{
   "key_one": "value_one",
   "key_two": "value_two",
   "key_three": "value_one-value_two"
}
```

**Describe the solution you'd like**

Support for this can be added to the existing `add_entries` processor (https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins/mutate-event-processors#addentryprocessor). The current configuration does not allow the `value` to be dynamic. 

I propose that we allow dynamic values similar to the opensearch sink `index` parameter, which supports injecting values from the Event into the index with `my-${some_event_key}-name`.

The add_entries processor would be configured to look like the following to complete the use case described above.

```
processor:
   - add_entries:
         entries:
            - key: "key_three"
              value: "${key_one}-${key_two}
```

which would result in the expected Event. The Event class has existing interface functionality to support this injection from the `add_entries` processor (https://github.com/opensearch-project/data-prepper/blob/5110699c993d4e17a56ae7d1f8c11def0429c0d9/data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/Event.java#L106), although it will only result in the value being created as a String, which can be mitigated with the `convert_type` processor if needed. 

**Describe alternatives you've considered (Optional)**
An ability to automatically support injection of Event values into any parameters by specifying that the value is of type `DynamicEventValue<T>`

This could be added as a data-prepper-plugin, and then in the plugin configuration for a processor, source, or sink, the configuration could use this plugin to automatically support injecting of values. For example, the add_entries config would change to 

```
private final String key;
private final DynamicEventValue<Object> value;
```

**Additional context**

**Comment by dlvenable** [comment]
@graytaylor0 , Is there any difference you see between this and #1380?

**Comment by graytaylor0** [comment]
> @graytaylor0 , Is there any difference you see between this and #1380?

I didn’t know that issue exists. I see no difference, but why add a new processor when we can just add more functionality to an existing processor?

**Comment by dlvenable** [comment]
I can see adding it here as well. We use the word `value` in a few places and it generally means a single concrete value, not a dynamic value.

Also, there is the consideration that the value isn't always a string.

I'm not against it, but I wonder if it would be clearer to users to have a clearly defined format processor.

**Comment by graytaylor0** [comment]
That does follow the precedent from the parse_json processor with ‘source’ and ‘pointer’, so I think that is a fair proposal
