### ISSUE TITLE
Support parsing Parquet formatted files from S3 (and other sources)

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#2445]
**Is your feature request related to a problem? Please describe.**

I may need to read [Parquet](https://github.com/apache/parquet-format)-formatted files from S3 buckets.

**Describe the solution you'd like**

Using the generic source codecs provided in #1532, have a `parquet` codec.

**Describe alternatives you've considered (Optional)**

Using the #1971 behavior, let S3 Select decode Parquet. However, this requires using this additional feature and may impact cost.

**Comment by dlvenable** [comment]
Closed by: #2727

**Comment by brian-grabau** [comment]
You added in input feature from s3 but what about a Parquet-formatted output to s3 for logs that are not in AWS but want to use s3 for long term storage?
