### ISSUE TITLE
Allow changing plugin names without breaking changes

### ISSUE THREAD

**Issue by asifsmohammed** [opensearch-project/data-prepper#2504]
**Is your feature request related to a problem? Please describe.**
Currently, if you want to rename a plugin it has to be a breaking change and there is no easy way to do it. 

**Describe the solution you'd like**
We can achieve this by adding `deprecatedName` to existing `DataPrepperPlugin` annotation (credits: @dlvenable). For example,
```
@DataPrepperPlugin(name = "otel_trace", deprecatedName="otel_trace_raw", pluginType = Processor.class, pluginConfigurationType = OtelTraceRawProcessorConfig.class)
```

**Describe alternatives you've considered (Optional)**
1. Duplicate the entire plugin package.
2. Duplicate the plugin class with `DataPrepperPlugin` annotation and create a new class with new name in `DataPrepperPlugin`.

**Comment by dlvenable** [comment]
We can also update the plugin framework to log a warning when it detects that a deprecated name is used.
