### ISSUE TITLE
Consistency in OTel plugin names

### ISSUE THREAD

**Issue by asifsmohammed** [opensearch-project/data-prepper#2515]
**Is your feature request related to a problem? Please describe.**
Data Prepper currently have multple plugins related to OTel but we don't follow any standard naming convention. 
For example, `otel_trace_source` and `otel_metrics_source`. 

Also, having processor keyword in a processor plugin is redundant. 
For example, `otel_metrics_raw_processor`

**Describe the solution you'd like**
All the plugins should follow a common naming convention, and we can leverage the https://github.com/opensearch-project/data-prepper/issues/2504 to make the changes without breaking anything.

Sources list,
`otel_trace_source` -> `otel_traces`
`otel_metrics_source` -> `otel_metrics`
`otel_logs_source` -> `otel_logs`

Processors list,
`otel_trace_raw` -> `otel_traces`
`otel_metrics_raw_processor` -> `otel_metrics`
`service_map_stateful` -> `service_map`

While it is allowed to have same name for a source and processor, I think it's a confusing user experience. Please comment if you have any suggestions.

**Comment by dlvenable** [comment]
@asifsmohammed , Data Prepper has two processors related to OTel traces.

* `otel_trace_raw`
* `otel_trace_group`

With the proposed change, it would then have:

* `otel_traces`
* `otel_trace_group`

This does not seem to provide any additional clarification. Can we find a better name? One that clarifies how this is different than `otel_trace_group`? And should we rename `otel_trace_group`?

**Comment by asifsmohammed** [comment]
@dlvenable I initially proposed changing `otel_trace_raw` to `otel_trace_span` but even that doesn't provide clarification. Looks like from the description of both the processors they do the same thing except the stateful processing. Maybe the description is inaccurate here.
`otel_trace_raw` - does stateful processing on extracting and filling-in trace group related fields
`otel_trace_group` - ills in the missing trace group related fields by looking up the OpenSearch backend

Let me know if you have any suggestions.

**Comment by dlvenable** [comment]
It seems that the difference here is between using stateful processing versus using OpenSearch? Shouldn't we reflect that in the names of the processors?

**Comment by asifsmohammed** [comment]
Yes we should. I don't think anyone has any ideas on the names here.
