### ISSUE TITLE
Accept data from Kafka

### ISSUE THREAD

**Issue by laneholloway** [opensearch-project/data-prepper#254]
Data Prepper can receive events from Kafka using a source which acts as a Kafka consumer.

This source should support most or all of the [consumer configurations](https://kafka.apache.org/25/documentation.html#consumerconfigs).

It should be able to support deserializing objects directly into Events. With the `StringDeserializer` it can create an Event with a single field, say `message` with the string as the value. It could possible have a JSON-based deserializer which maps JSON data directly into the fields of the Event.

**Comment by srakshit** [comment]
I'm waiting for the feature when Data Prepper can talk to Kafka/MSK.

**Comment by ryn9** [comment]
Would like to see Kafka as both and input and a sink

**Comment by dlvenable** [comment]
This is implemented and will be released in 2.4.
