### ISSUE TITLE
[BUG] S3 source backoff is still quite aggressive

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#2568]
**Describe the bug**

Failures in the `s3` source related to authentication tend to require user intervention. Because of this, the backoff for situations with authentication issues is more aggressive than it needs to be.

This produces a number of unnecessary logs before the user can respond.

**Expected behavior**

Have a longer delay for STS and unauthenticted errors.

**Comment by dlvenable** [comment]
Re-opening to address this comment: https://github.com/opensearch-project/data-prepper/pull/2574#issuecomment-1518725729

**Comment by dlvenable** [comment]
@asifsmohammed , Regarding this comment (https://github.com/opensearch-project/data-prepper/pull/2574#issuecomment-1518725729):

> Looks good to me. One more place we can use backoff is `S3ObjectWorker` when we read from S3. We don't handle `StsException` gracefully here. This is extremely rare case because temporary credentials are cached (when a successful call is made to read messages from SQS) there is still a chance it might expire when calling `getObject`.
> 
> https://github.com/opensearch-project/data-prepper/blob/5dadde406be4038c6808795dcf4b6367e040f5b3/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ObjectWorker.java#L89

I looked over the code and I'm not sure there is really anything we'd want to do differently. There is only one role used by both the SQS and S3 workers.

So if the STS role expires during this time, we might have an `StsException`. However, it goes right back to the loop and will very quickly call `ReceiveMessages`. However, that fails and the initial backoff begins. So, this can result in at most two STS requests happening back-to-back.

What do you think?

Currently, the `StsException` is suppressed here, so we'd have to handle it here.

https://github.com/opensearch-project/data-prepper/blob/aef2baa3ec0a0aca7e74026db18553e0ef9eda8a/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java#L255-L264

**Comment by dlvenable** [comment]
Actually, this happens in a loop as well.

https://github.com/opensearch-project/data-prepper/blob/aef2baa3ec0a0aca7e74026db18553e0ef9eda8a/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java#L239

So this can be up to 10 requests.

**Comment by asifsmohammed** [comment]
I'm fine with making just 2 calls before backoff kicks in. 

> Currently, the StsException is suppressed here, so we'd have to handle it here.

If `S3ObjectWorker` throws `StsException` for each message (maximum of 10 messages) we return `Optional.empty()` for each message and read the message again when it's available. So there are a maximum of 10 * 5 calls if there is `StsException`

> 10 - max messages
> 5 -retry count

https://github.com/opensearch-project/data-prepper/blob/aef2baa3ec0a0aca7e74026db18553e0ef9eda8a/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java#L255-L264

One more place I could think is here when we delete messages.
https://github.com/opensearch-project/data-prepper/blob/aef2baa3ec0a0aca7e74026db18553e0ef9eda8a/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java#L270

**Comment by dlvenable** [comment]
@asifsmohammed , Also, that 5x multiplier will not occur from what I see.

The AWS only retries for certain status codes:

https://github.com/aws/aws-sdk-java-v2/blob/a8c7d397d6f141ff86d8e91de82e2bfd12fbafe6/core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/conditions/RetryCondition.java#L47-L53

This is defined here:

https://github.com/aws/aws-sdk-java-v2/blob/a8c7d397d6f141ff86d8e91de82e2bfd12fbafe6/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/SdkDefaultRetrySetting.java#L72-L77

So bad request, unauthenticated, and forbidden will not retry.
