### ISSUE TITLE
[BUG] OpenSearch Sink failures are masked by max retry in the logs

### ISSUE THREAD

**Issue by cmanning09** [opensearch-project/data-prepper#2597]
**Describe the bug**
Writing to the OpenSearch sink may encounter failures. These were originally provided after the final failure occurred. The recent change to the failure handling overwrites the error message masking it from the operator. This makes it difficult to debug failure scenarios:
```
WARN  org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink - Document [******] has failure.
java.lang.RuntimeException: Number of retries reached the limit of max retries(configured value 10)
```

**Expected behavior**
Log the original failure associated with 

**Additional context**
- [Overwriting the original failure](https://github.com/opensearch-project/data-prepper/blame/74dbff0835298cee3ddf2cef9fb20be8baa755b2/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java#L190)
- [PR associated with the change](https://github.com/opensearch-project/data-prepper/pull/2339)

**Comment by kkondaka** [comment]
I will look into this. Please assign this to me.

**Comment by dlvenable** [comment]
Thanks, @kkondaka !

Along with this change, it may be useful to log periodically. Right now, if the sink continues to fail before reaching `max_retries` there is no indication in the logging. You can find this in the metrics however.

Perhaps every 5-10 failures log a message about failing to write.
