### ISSUE TITLE
Support parsing User-Agent fields

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#2618]
**Is your feature request related to a problem? Please describe.**

Many use-cases seek to parse out User-Agent headers to get useful metadata before saving to OpenSearch. This can include the type of browser, version information of the browser, the operation system, version information for the operating system, and even device information.

**Describe the solution you'd like**

Provide a processor for parsing User-Agent headers.

```
useragent:
  source_key: /headers/user_agent
  target_key: /user_agent
  exclude_original: false
```

Following along with https://github.com/opensearch-project/observability/issues/1398, this should support ECS-compatibility.

In the example above, I might have output which looks like the following:

```
user_agent : {
  name: "Safari",
  version: "16.4",
  device: {
    name: "iPhone"
  },
  original: "..."
}
```

Fields:

* `source_key` - The key path to use for the User-Agent string. required
* `target_key` - The key path which will be the object containing the User-Agent metadata. Optional: if not specified, defaults to `user_agent` to match the ECS schema.
* `exclude_original` - By default, the source_key will be copied. Set this to `true` to not copy it. Optional; defaults to `false`.

**Additional context**

ECS reference for User-Agent: https://www.elastic.co/guide/en/ecs/current/ecs-user_agent.html#field-user-agent-device-name

**Comment by kkondaka** [comment]
@oeyh Is it not possible to achieve this using grok processor?

**Comment by oeyh** [comment]
@kkondaka In theory it can, but that will be too complicated. This is the [regexes](https://github.com/ua-parser/uap-core/blob/master/regexes.yaml) that `uap-java` uses to parse user agent string. You can see how many pattern variants there can be for a user agent string.
