### ISSUE TITLE
Support getting the length of a string in expressions

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#2639]
**Is your feature request related to a problem? Please describe.**

I'd like to create conditionals based on the length of a string.

**Describe the solution you'd like**

Provide a function to get the length of a string from a key.

```
length("/log_level") > 10
```

**Describe alternatives you've considered (Optional)**

We could have a length processor. But, this approach would be more compact.

**Additional context**

Base this on #2626

**Comment by dlvenable** [comment]
Completed by #2644.

**Comment by kkondaka** [comment]
Completed by #2726
