### ISSUE TITLE
[BUG] Unhelpful error message when failing to authenticate with Amazon OpenSearch Service

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#2655]
**Describe the bug**

Data Prepper is showing an error that looks like the following:

```
[security_exception] authentication/authorization failure
```

**Expected behavior**

Data Prepper used to have a clearer error:

```
[security_exception] no permissions for [indices:admin/get] and User [name=arn:aws:iam::123456789012:role/FullAccess, backend_roles=[arn:aws:iam::123456789012:role/FullAccess], requestedTenant=null]
```

Additionally, the OpenSearch username or STS role should always be included in the response.

For example:

> The role "arn:aws:iam::123456789012:role/FullAccess" was unable to authenticate with the OpenSearch domain. Please check your permissions.

**Comment by dlvenable** [comment]
This appears to be coming from :

```
https://github.com/opensearch-project/opensearch-java/blob/e422eb0263847bd1ca867c8c109bbb15463fae5b/java-client/src/main/java/org/opensearch/client/transport/aws/AwsSdk2Transport.java#L452-L453
```

**Comment by dlvenable** [comment]
See #2657 for a similar problem with username/password authentication.

**Comment by chenqi0805** [comment]
Opened an issue in opensearch-java: https://github.com/opensearch-project/opensearch-java/issues/473.

**Comment by dlvenable** [comment]
@chenqi0805 , Is it possible to detect that an authentication issue occurred and then log the following message even without https://github.com/opensearch-project/opensearch-java/issues/473?

> The role "arn:aws:iam::123456789012:role/FullAccess" was unable to authenticate with the OpenSearch domain. Please check your permissions.

It would be nice to add this additional logging in v2.3.
