### ISSUE TITLE
Add support for String Expressions in DataPrepper Expression

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/data-prepper#2686]
**Is your feature request related to a problem? Please describe.**
Add support to allow expressions returning String type. Also add string operations, like string concatenation using "+" as operator

**Describe the solution you'd like**
Suggested grammar change for supporting String Expressions

```
stringExpression
    : stringExpression PLUS stringExpression
    | function
    | JsonPointer
    | String
```

This allows for following expressions
```
 getMetadata("key") + "suffix"

/key + "suffix"

```

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by kkondaka** [comment]
This issue will be addressed in two phase. Phase 1 will add support for expressions returning strings from string literals or json pointers or functions. Second phase will address concatenation operation on strings.

**Comment by dlvenable** [comment]
@kkondaka , Is this issue complete?
