### ISSUE TITLE
[BUG] S3 source silently drops data with files contain a single JSON element

### ISSUE THREAD

**Issue by cmanning09** [opensearch-project/data-prepper#2699]
**Describe the bug**

**To Reproduce**
1. Create an S3 pipeline with json codec
3. Upload a test file with just a json item not in an array. Ex: `{"foo": "bar"}`
4. Verify the S3 source read the data in the logs
```
INFO  org.opensearch.dataprepper.plugins.source.SqsWorker - Received 1 messages from SQS. Processing 1 messages.
INFO  org.opensearch.dataprepper.plugins.source.S3ObjectWorker - Read S3 object: [bucketName=****, key=****.json]
INFO org.opensearch.dataprepper.plugins.source.SqsWorker - Deleted 1 messages from SQS. [****]
```
6. View metrics, No data will be written to the opensearch nor the buffer. The logs do not detail the data was dropped or is missing.

**Expected behavior**
An indication that there was a failure reading the data

**Comment by dlvenable** [comment]
Was there an array at all? We could have some sort of indication when there is a JSON without an array - that seems a reasonable approach.

I'm somewhat concerned about having a metric when the there is an array and some data outside that array. It may lead to new confusion for customers.

Also, I created #2700 to support nd-json. This should help for many users.

**Comment by cmanning09** [comment]
There was no array at all. The file maybe a `nd_json` file with a single line. I am not sure if it is though.

Thanks for creating #2700 @dlvenable

**Comment by cmanning09** [comment]
If we feel a metric may be too much. I would like to propose we add a log line for data found which does not start with a JSON Array [here](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/codec/json/JsonInputCodec.java#L45).

I am thinking something along the lines of:

```
        while (!jsonParser.isClosed() && jsonParser.nextToken() != JsonToken.END_OBJECT) {
            if (jsonParser.getCurrentToken() == JsonToken.START_ARRAY) {
                parseRecordsArray(jsonParser, eventConsumer);
            } else {
                Log.warn("Data found outside of a JSON array. `json` codec only supports translating JSON Array elements");
            }
        }
```

**Comment by dlvenable** [comment]
When I suggested a metric, I meant that if the JSON codec doesn't find _any_ array. And a warning could go along with it.

I'm not sure if we want a warning when it finds an array and other data. That seems it could be a false warning because it could be part of some formats.

If we do add a warning though, you can't do it in the else because this finds any different tokens - you'd get a lot of errors. I think you'd have to find a token pointing to object or literal values and then mark that you found some non-array item.

**Comment by dlvenable** [comment]
> When I suggested a metric, I meant that if the JSON codec doesn't find any array. And a warning could go along with it.

On second hand, we do technically have this data. There is already a metric counting the number of items. Perhaps monitoring the metric for a minimum value of 0 would give the same results. So maybe no metric makes sense here either.

**Comment by cmanning09** [comment]
You are right, this could be noisy because we are iterating over each character in the JSON until we find a JSON Start Array char.

> On second hand, we do technically have this data. There is already a metric counting the number of items. Perhaps monitoring the metric for a minimum value of 0 would give the same results. So maybe no metric makes sense here either.

I assume you are referring to `s3ObjectsEvents`. This summary metric is difficult to interpret a failure occurred. Min value of 0 could be due to the ingestion data having an invalid format or a node in the pipeline was not processing data. This would be extremely hard to catch while a pipeline is processing data. I think a separate metric may help here for failures.
