### ISSUE TITLE
[BUG] S3 Scan Range Paramter is unused in the code

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#2739]
**Describe the bug**
Using `range` with s3 scan does not use the `range` parameter

https://github.com/opensearch-project/data-prepper/blob/d0d7ba01d179b60d153ff54865c7924a133a7358/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanService.java#L74 should be used in the partition supplier here (https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplier.java)

**Expected behavior**
Range parameter scans from start_time plus range or from end_time - range

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

**Comment by oeyh** [comment]
@graytaylor0 Not sure if someone has fixed it, I can see `range` parameter being used among those lines:
https://github.com/opensearch-project/data-prepper/blob/10d398446f933dffed77250160528f19e81851d5/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/ScanOptions.java#L112-L125

Also verified that `range` is used by running some local test pipelines.

The README for S3 Scan options looks messy. I will clean that up instead.
