### ISSUE TITLE
Add a function in the DataPrepper Expressions to check if a string contains another string

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/data-prepper#2804]
**Is your feature request related to a problem? Please describe.**
Add a function in the DataPrepper Expressions to check if a string contains another string. This is useful to check if a field in the event has a particular prefix/suffix/substring in it.

**Describe the solution you'd like**
Proposal is to add `containsSubstring` function to DataPrepper expressions which can take string literal or a json pointer to check if a string contains another string as it's substring. 
The function signature is as follows
```
boolean containsSubstring(String string1, String string2)
```
It returns true if the string in the `string2` is a substring of `string1`, Otherwise it returns false.

It can be used in the following 4 ways
```
containsSubstring(/jsonPointer, "stringLiteral")
containsSubstring("stringLiteral", /jsonPointer)
containsSubstring("stringLiteral1", "stringLiteral2")
containsSubstring(/jsonPointer1, /jsonPointer2)
```

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by cmanning09** [comment]
I think we should make a decision on how'd we want our expressions to look long term now. Do we want common methods or specific type methods. For example: Do we want to support a single function called `contains` which can support only `strings` and `jsonPointers` referencing `strings` in this first iteration.  But then can be extended to support other data types like `sets`, `maps`, etc. in future revisions. Or do we want to have separate functions for  different data types? I see the benefits and draw backs of both. Have we decided on how we will approach this?
