### ISSUE TITLE
Ability to use Data Prepper expressions in the OpenSearch sink index and document_id_field

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#2864]
**Is your feature request related to a problem? Please describe.**
The OpenSearch sink currently supports using values from an Event in the `index` and `document_id_field`

```
index: "${key_one}-${key_two}-%{yyyy.mm.hh}
document_id_field: "/key_three"
```

As a user, I would like the ability to set the index and document_id_field from Data Prepper expressions, most notably the functions available. For example, I would like to use the `getMetadata` function to set these values without having to keep them in the Event.

**Describe the solution you'd like**
A way to use Data Prepper expressions along with formatting in these parameters. We should do this in a way that can be kept consistent in any location in the pipeline config that needs a value

For the `add_entries` processor, we created a new field for each of these options

```
add_entries:
   - entries: 
         key: "/my_key"
         value: "static_value"
         format: "${key_one}-${key_two}"
         value_expression: "length(/message)"
```

Ideally, we would not repeat this pattern in every location, in this case that being

```
index: "my_index" # This currently supports format as well with ${}
index_expression: "getMetadata(\"metatdata_key\")"
document_id_field: "/my_field_from_event"
document_id_field_expression: "getMetadata(\"metadata_key_two\")"
document_id_field_format: "${key_one}-${key_two}"
```

Instead of this, we should try to consolidate as mentioned in #2719. So we should have only the `index` and `document_id_field` parameters, and they will support all of the above options

The best way to do this will be to use ${} syntax to escape both keys and expressions. For example,

```
index: "prefix-${/some/key}-${getMetadata(\"metadata_key\")}-%{yyyy.mm.hh}
document_id_field: "prefix-${/some/key}-${length(/message)}"
```

Alternatively, we could consider a different escape character between key values and expressions if we find it difficult to detect keys vs expressions

```
index: "prefix-${/some/key}-@{getMetadata(\"metadata_key\")}-%{yyyy.mm.hh}
document_id_field: "prefix-${/some/key}-@{length(/message)}"
```

**Describe alternatives you've considered (Optional)**

**Additional context**
Consolidating the expression use in parameters of Data Prepper pipeline configurations (https://github.com/opensearch-project/data-prepper/issues/2719)

**Comment by dlvenable** [comment]
@graytaylor0 , Isn't this a breaking change?

It seems that we should add a new `document_id` which has the behavior you specified and deprecate the `document_id_field` property. The `_field` suffix of `document_id_field` is indicating that the value comes from the specified field.

Now, the behavior is to set the document_id to some value, which can use an expression of the field.
