### ISSUE TITLE
[BUG] Data prepper 2.3.2 is stuck in Submitting request to initiate the pipeline processing

### ISSUE THREAD

**Issue by pankdhnd** [opensearch-project/data-prepper#3043]
**Describe the bug**
We have deployed TLS enabled data prepper version 2.3.2 on Kubernetes cluster and we are using opensearch sink for it. We use data prepper for distributed tracing using opentelemetry. We noticed that once the pod starts up, it the data prepper containers always gets stuck at "Submitting request to initiate the pipeline processing" and never comes out of it

**To Reproduce**
1. Deploy data prepper 2.3.2 with attached pipeline configuration

**Expected behavior**
Data prepper starts up

**Attachments**
Data prepper console logs, data prepper configuration

**Environment (please complete the following information):**
- Kubernetes cluster (EKS)
[data-prepper-logs.txt](https://github.com/opensearch-project/data-prepper/files/12093613/data-prepper-logs.txt)
[data-prepper-tracing-pipeline.txt](https://github.com/opensearch-project/data-prepper/files/12093621/data-prepper-tracing-pipeline.txt)

**Comment by dlvenable** [comment]
@pankdhnd , Is Data Prepper 2.3.2 processing data for you? I suspect this was just a change to the logging Data Prepper produces when starting up.

**Comment by pankdhnd** [comment]
Right, data is passing through prepper. I got confused with the message and assumed that prepper is stuck.
Closing this issue.
