### ISSUE TITLE
[Enhancement] Support serverless compatible index template in opensearch sink

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#3048]
**Is your feature request related to a problem? Please describe.**
Currently opensearch sink defaults to `management_disabled` for index management. Since the merge of support for composable index template we have the ability to expand the support for index management for serverless ingestion.

**Describe the solution you'd like**

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by dlvenable** [comment]
Added to 2.5.0 by backport PR #3467.
