### ISSUE TITLE
Rename Prepper to Processor

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#311]
**Is your feature request related to a problem? Please describe.**

Data Prepper currently supports `prepper` plugins. This term is not entirely clear. Additionally, it is somewhat ambiguous with Data Prepper.

**Describe the solution you'd like**

Rename `prepper` to `processor`.

This can be done in a phased approach. First, we will add `processor` as a supported name within the pipeline YAML configuration. We will continue to support either `processor` or `prepper` in the YAML. However, only one may be present per pipeline.

In a major release version of Data Prepper we will remove `prepper` so that only `processor` is allowed.

Additionally, we will add a new interface `Processor` with the same signature as `Prepper`. The `Prepper` interface will be made to inherit from `Processor` and will be deprecated. In a major release of Data Prepper, we will remove the `Prepper` interface.

**Comment by chenqi0805** [comment]
@dlvenable FYI, we have a product level decision on this naming: https://github.com/opendistro-for-elasticsearch/data-prepper/issues/209 .

**Comment by laneholloway** [comment]
@chenqi0805 We had a discussion with Rajiv over it and he'd like it changed back to processor.

**Comment by dlvenable** [comment]
Data Prepper can rename Prepper to Processor as a non-breaking change by using inheritance. Data Prepper can have a new `Processor` interface and all the existing methods in `Prepper` can be moved there. Then `Prepper` will extend `Processor`. A similar change would need to happen for `AbstractPrepper`.

Then `Prepper` and `AbstractPrepper` can be marked `@Deprecated`. Existing plugins in the core project should use `Processor`.

All code in Data Prepper Core which uses `Prepper` needs to change to use `Processor` so that this is the true base class used in the core framework.

Additionally, the pipeline parser code must be able to read both `processor:` and `prepper:` in the pipeline configuration. However, only should be provided in any given configuration since the order is critical in pipelines.

**Comment by graytaylor0** [comment]
I feel like there are more important things to be done than spending time renaming back to Processor.

**Comment by dlvenable** [comment]
@graytaylor0 , That makes sense for prioritization, and perhaps this would be deferred until a later version. But, does the term `Processor` help better convey its purpose to Data Prepper users and plugin authors?

**Comment by graytaylor0** [comment]
@dlvenable I would agree that `Processor` would be more quickly understood by those who are new to Data Prepper. But without `preppers` it makes the name itself of `Data Prepper` feel pretty random. With that logic,`Data Processor` would've done a better job conveying what it is, but that name is too generic. So although `Processor` is better, I think consistency with the name might end up keeping people from getting confused.

**Comment by graytaylor0** [comment]
It was mentioned above that Rajiv would like it changed back to processor. He could have good reasoning for this that would be helpful to hear.

**Comment by dlvenable** [comment]
Removal of `processor` will be done in #619 , which is scheduled for 2.0.

**Comment by dlvenable** [comment]
Data Prepper core still uses the `Prepper` interface. Not all `Processor` implementations will implement `Prepper`, and thus there will be errors for any plugin which implements only `Processor`. I'm re-opening this issue to update Data Prepper core to use `Processor` exclusively.
