### ISSUE TITLE
[BUG] CloudWatch Logs Sink not generating LogEventSuccessMetrics

### ISSUE THREAD

**Issue by MaGonzalMayedo** [opensearch-project/data-prepper#3113]
**Describe the bug**
When collecting metrics from CloudWatch Logs, if there are no event_handles in the source type, the sink does not properly update the "LogEventsSucceededCounter".

**To Reproduce**
1. Set up Data-Prepper config with http source and cloudwatch_logs sink and configured CloudWatch metrics.
2. Sent POST requests with log information to Data-Prepper server instance.

**Expected behavior**
When reading the collected metrics from the sink, a positive value for the events succeeded was expected as log events were being received. But instead received 0 for the entire logging period.

**Screenshots**
![image](https://github.com/opensearch-project/data-prepper/assets/95880281/5459b0f9-d6fc-4288-ae61-932a8ec7c173)

**Environment (please complete the following information):**
 - OS: macOS Ventura
 - Version 13.4

**Comment by dlvenable** [comment]
Closed by #3114.
