### ISSUE TITLE
Support s3:// prefix in S3 bucket names

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#3143]
**Is your feature request related to a problem? Please describe.**

The `s3` source and `s3` sink require the bucket name to be supplied only as a bucket name. Some users have provided the `s3://` scheme in front and then hit errors.

**Describe the solution you'd like**

Allow the `s3://` prefix and remove it from the bucket name supplied to the AWS SDK if it is supplied.

**Describe alternatives you've considered (Optional)**

An alternative is to have a specific validation on `s3://` and tell the user very clearly that they should remove it.

**Comment by dlvenable** [comment]
The solution here should also be included in the DLQs.

**Comment by asifsmohammed** [comment]
https://github.com/opensearch-project/data-prepper/pull/3156
