### ISSUE TITLE
Add additional index_types

### ISSUE THREAD

**Issue by mishavay-aws** [opensearch-project/data-prepper#3148]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. It would be nice to have [...]

As an administrator configuring collectors that write to OpenSearch you want to configure index management policies scoped to particular index-name pattern. 

**Describe the solution you'd like**

Define index_type for "otel_logs_source" and "otel_metrics_source" (and others) similar to ones defined for "[trace-analytics-raw](https://github.com/opensearch-project/data-prepper/blob/28fdf903b791ec7365e5783022b859a7910040eb/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexType.java#L15)" and "[trace-analytics-service-map](https://github.com/opensearch-project/data-prepper/blob/28fdf903b791ec7365e5783022b859a7910040eb/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexType.java#L16C1-L16C5)"

**Describe alternatives you've considered (Optional)**

Without index_type defined, an index needs to be explicitly named, where it complicates creation of a scoped down policy in OpenSearch. 

**Additional context**

**Comment by dlvenable** [comment]
This is a good idea. We'll want to be sure to align the approach with the OpenSearch simple schema that the observability plugin is supporting.

**Comment by juergen-walter** [comment]
@dlvenable is there a time horizon you want to tackle this feature? Or any blockers?

I could not find it on the timeline https://github.com/opensearch-project/data-prepper/projects/1

**Comment by juergen-walter** [comment]
Solution should incorporate the changes from https://github.com/opensearch-project/data-prepper/issues/3342

**Comment by juergen-walter** [comment]
There is a PR https://github.com/opensearch-project/data-prepper/pull/3929 for OpenTelemtry logs and metrics, reviews appreciated

**Comment by linghengqian** [comment]
This looks like a great PR. Does the OpenSearch Dashboard side have any pre-built visualization panels that correspond to this?
