### ISSUE TITLE
[BUG] Missing Configuration details in Kafka documentation

### ISSUE THREAD

**Issue by cmanning09** [opensearch-project/data-prepper#3157]
**Describe the bug**
Kafka ReadMe does not detail configuration options like:
1. `broker_configuration_type`
2. `aws_msk_iam`
3. `ssl_endpoint_identification_algorithm`
4. `AwsIamAuthConfig.role`
5. `key_mode`

This is not an inclusive list. I only looked through a handful of configuration options and found these. There may be others.

**Additional context**
[Documentation Website](https://github.com/opensearch-project/documentation-website/pull/4737) is lacking details as well. It has some of these but is missing some as well and needs to be thoroughly reviewed.

**Comment by cmanning09** [comment]
There are no details for metrics provided by the Kafka Source plugin.

**Comment by dlvenable** [comment]
These details should go into the documentation and we'll want to avoid duplication in the README.

**Comment by dlvenable** [comment]
I moved this to the 2.5 release. Let's clean up the README.md and make sure that the documentation has the correct information.

**Comment by ict-one-nl** [comment]
Also the configuration details are different between the docs and the test files. 

https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sources/kafka/ look at the encryption entry.

This differs from
https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/kafka-plugins/src/test/resources/sample-pipelines.yaml 

Trying to disable SSL seems to fail either way :)

**Comment by kkondaka** [comment]
`broker_configuration_type`, `aws_msk_iam` and `key_mode` are documented. `aws_msk_iam: "role"` is also documented. `ssl_endpoint_identification_algorithm` is not applicable to kafka source. It should be documented when kafka sink is made available
