### ISSUE TITLE
BlockingTaskExecutor is never used in Otel-Trace-Source

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#316]
**Describe the bug**
Although configured in ServerBuilder: https://github.com/opensearch-project/data-prepper/blob/1cb44e1094ac7428130f75a5b01fe55aeeb09283/data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSource.java#L107
BlockingTaskExecutor is not used by default to execute GRPC service: https://armeria.dev/docs/server-grpc#blocking-service-implementation
This leads to blocking tasks executed directly on main EventLoop thread that blocks event handling in netty framework. Also, as a consequence, `threads` parameter never actually works in the source plugin.

**To Reproduce**
Do not have way to reproduce in data-prepper context. But it is expected to severely delay the new request handling.

**Expected behavior**
We should useBlockingExecutor in grpcServiceBuilder:

```
final GrpcServiceBuilder grpcServiceBuilder = GrpcService
                    .builder()
                    // explicitly use blocking task executor
                    .useBlockingTaskExecutor(true)
                    .addService(new OTelTraceGrpcService(
                            oTelTraceSourceConfig.getRequestTimeoutInMillis(),
                            buffer,
                            pluginMetrics
                    ))
                    .useClientTimeoutHeader(false);
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

**Comment by chenqi0805** [comment]
I would like to put it on the milestone for 1.3 as it affects trace ingestion performance

**Comment by dlvenable** [comment]
I'm not sure I follow this. What is this block of code doing?

https://github.com/opensearch-project/data-prepper/blob/1cb44e1094ac7428130f75a5b01fe55aeeb09283/data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSource.java#L107-L109

**Comment by dlvenable** [comment]
I just saw the PR. So Armeria lets you set the blocking task executor, but doesn't use it unless you also call `.useBlockingTaskExecutor(true)`?

**Comment by chenqi0805** [comment]
> I just saw the PR. So Armeria lets you set the blocking task executor, but doesn't use it unless you also call `.useBlockingTaskExecutor(true)`?

Correct. Or annotate the service class as we already did in http source: https://github.com/opensearch-project/data-prepper/blob/08def2ec297540e9a9a70a2bff5a60cac87da5ed/data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/LogHTTPService.java#L39
