### ISSUE TITLE
[BUG] Remove include/exclude keys from codecs

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#3176]
**Describe the bug**

Several `OutputCodec` configurations have include or exclude key options. These should not exist.

**Expected behavior**

Remove old configurations from code, READMEs, and documentation (if applicable). Do for all `OutputCodec` implementations.

**Comment by asifsmohammed** [comment]
All the `include_keys` and `exclude_keys` configurations  are only in `SinkModel`. No need to make any changes in OutputCodec

**Comment by dlvenable** [comment]
Thank you for confirming that, @asifsmohammed !
