### ISSUE TITLE
[Documentation] Remove unsupported 'acknowledgements_timeout' option from kafka source config guide

### ISSUE THREAD

**Issue by hshardeesi** [opensearch-project/data-prepper#3246]
**Is your feature request related to a problem? Please describe.**

Kafka source plugin does not support 'acknowledgements_timeout' config option, it should be removed from plugin's config guide: https://opensearch.org/docs/2.9/data-prepper/pipelines/configuration/sources/kafka/

**Comment by dlvenable** [comment]
I created a PR for the documentation:

https://github.com/opensearch-project/documentation-website/pull/4898

**Comment by dlvenable** [comment]
The above PR is approved and merged.
