### ISSUE TITLE
[Unit Test] Remove sleeps from KafkaSourceCustomConsumerTest

### ISSUE THREAD

**Issue by hshardeesi** [opensearch-project/data-prepper#3263]
Multiple unit tests in KafkaSourceCustomConsumerTest have Thread.sleep(10s). This increases the data prepper build time. Sleep appears to be present for acknowledgements framework to complete acknowledgements. This sim is to track improvement in the unit-tests to mock acknowledgement framework apis and remove Thread.sleep().

**Comment by dlvenable** [comment]
@kkondaka , Did you resolve this? I think you were working on this some recently.

**Comment by kkondaka** [comment]
Resolved by https://github.com/opensearch-project/data-prepper/pull/3358
