### ISSUE TITLE
[core] Merging PipelineDataflowModel instead of pipeline YAML files

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#3289]
**Is your feature request related to a problem? Please describe.**
Currently user is allowed to distribute pipeline configuration bodies across multiple YAML files and Data Prepper will merge them together before converting into internal PipelineDataflowModel. This will require any shared pipeline configuration to be applied to all pipeline config files even if it is only defined in one of those files. Thus blurring the usage of pipeline config file versus data prepper config file which is supposed to include global settings.

**Describe the solution you'd like**
Instead of merging the pipeline config body from files together, we should first parse each file into its own PipelineDataflowModel and then merge them into a single PipelineDataflowModel.

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by dlvenable** [comment]
I also think this resolves a few issues which I've seen:

* When using multiple pipelines, the line numbers are only accurate for the first file loaded.
* The version property does not work with multiple files.
