### ISSUE TITLE
[BUG] Enums are not being deserialized correctly for all plugins

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#3376]
**Describe the bug**
Due to some jackson dependabot update, but deserializing Enums does not work in `data-prepper-core` for all plugins now

I noticed this when Enum deserialization for the opensearch source mysteriously started failing with 

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Cannot construct instance of `java.lang.Enum` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
``` 

for the `search_context_type`. I manually fixed that but the http sink `http_method` also does not work (not sure if it worked before). There may be other places where enums would fail to deserialize too now

**To Reproduce**
Create a pipelines with http sink and `http_method` will not deserialize

```
sink:
  - http:
      http_method: "POST"
      url: "test-url"
```

Same fails for sqs `notification_type`

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

**Comment by oeyh** [comment]
Ran into the same issue on `main` branch with enum field (`TargetType`) in `translate` and `convert_entry_type` processors. Same for enum field `flattened_element` in `list_to_map` processor. It's possible all enum fields are being affected. 

Also tested on `2.4` branch, everything seems OK.

**Comment by kkondaka** [comment]
That's interesting. So, some bug was introduced in 2.5? @dlvenable any idea what could be causing this?

**Comment by dlvenable** [comment]
My initial guess is that something changed in Jackson and we pulled this in with one of our dependency updates.

@oeyh , Were there any changes on the `2.4` branch since your testing which might relate to Jackson?

**Comment by asifsmohammed** [comment]
Looks like there are couple of changes in `data-prepper-core` parser recently which might be causing this, I might be wrong. These changes are introduced in `2.5` branch
https://github.com/opensearch-project/data-prepper/tree/2.5/data-prepper-core/src/main/java/org/opensearch/dataprepper/parser

**Comment by dlvenable** [comment]
I just tested against the released 2.4.1 Docker image to double check. I can verify that the following enums work in it: `source.s3.notification_type`, `source.s3.compression`, `sink.s3.compression`, `sink.s3.buffer_type`.

**Comment by dlvenable** [comment]
I think the problem here is the inclusion of `Enum` in the `ObjectMapperConfiguration` for variable injection.

https://github.com/opensearch-project/data-prepper/blob/b47b3d5a7a0bd450cdf8121926ed009e6fdbe0fd/data-prepper-core/src/main/java/org/opensearch/dataprepper/plugin/ObjectMapperConfiguration.java#L20

@chenqi0805 , Do you have any concerns with removing `Enum` from here for now? This means that you can't use environment variables or AWS Secrets Manager for enum values, which is probably fine.

**Comment by dlvenable** [comment]
We should probably also remove `Duration`. I'd guess the Data Prepper duration deserializer is not in use as a result.

**Comment by chenqi0805** [comment]
@dlvenable I do not have particular concern on removing `Enum` since we are parsing it as String mostly. But I am not sure about `Duration`

**Comment by chenqi0805** [comment]
@dlvenable On a second thought, we might be OK to document that Duration and Enum are not supported for secrets.
