### ISSUE TITLE
Improve sink failure log messages

### ISSUE THREAD

**Issue by hshardeesi** [opensearch-project/data-prepper#3379]
**Is your feature request related to a problem? Please describe.**
Opensearch sink failure log messaging is not descriptive enough to root cause issues.

Sample log message:
```
org.opensearch.dataprepper.plugins.sink.opensearch.BulkRetryStrategy - Bulk Operation Failed. Number of retries 25. Retrying...
```

**Describe the solution you'd like**
More details should be added to the log, few suggestions are:
- What is reason for operation failure.
- Whats the response code from opensearch domain.
- How many individual records failed and how many succeeded in bulk request.
- Which index bulk operation failed for. 
- Opensearch domain URL.
- Request duration.
- Number of records/bytes sent in the bulk operation that failed

**Comment by jw-amazon** [comment]
Yes, definitely like to see this improvement !

**Comment by kkondaka** [comment]
Fixed in PR https://github.com/opensearch-project/data-prepper/pull/3532
