### ISSUE TITLE
S3 Scan with acknowledgments waits for acknowledgment before processing another object

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#3381]
**Is your feature request related to a problem? Please describe.**
S3 scan waits for the acknowledgment to be received for an object before it starts processing another. This leads to lower performance and not utilizing the data prepper buffer to its full extent.

**Describe the solution you'd like**
S3 Scan should continue grabbing objects and writing them to the buffer instead of waiting for the acknowledgment before processing the next object.

This will require some modifications to source coordination to allow for partitions to be put into a certain state when an ack is being waited on to ensure that no other nodes pick it up, and still allows the current node to mark the partition as completed.

A potential solution for this would be to introduce another status for partitions, WAITING_ON_ACK.

When a node finishes writing the entirety of a partition to the buffer, it would put the partition in the WAITING_FOR_ACK state with an hour timeout. Once this hour timeout is reached, the partition will become available for other nodes to pick up. The node that set this partition in the WAITING_FOR_ACK state would have an hour of ownership over it to complete it in the acknowledgment timeout.

The acknowledgment callback would then mark the partition as completed and do whatever else is needed. This will require two new methods to the SourceCoordinator interface. 

```
markAsWaitingForAck(final String partitionKey, final Duration acknowledgmentTimeout)
```

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by sharraj** [comment]
WAITING_ON_ACK cleanup can happen by Ack infra on the Ack timeout. That way we rely only on one time which is Ack timeout. Once this state is removed in case if Ack timesout, partition is available to be grabbed again.

**Comment by graytaylor0** [comment]
One idea that may be simpler is just adding the following function to source coordinator without the need for a new status

`markPartitionForAckWait(String partitionKey, final Duration ackTimeout).` This function will just update the partitionOwnershipTimeout for the partition to be owned for the ackTimeout amount of time (will be 1hr) to ensure that the partition isn’t picked up by another node. Then at the end of the hour if partition is not completed by the ack callback then another node would pick it up.
