### ISSUE TITLE
[BUG] Insufficient permissions to AOS shuts down DataPrepper when a dynamic index pattern is used

### ISSUE THREAD

**Issue by engechas** [opensearch-project/data-prepper#3393]
**Describe the bug**
As part of the sink initialization process, DataPrepper will attempt to create static indices. This also serves as a permissions check for the DataPrepper -> AOS integration. However, if a dynamic index pattern is used, no indices are created during initialization and instead permissions gaps are exposed at runtime by shutting down the pipeline:

```
ERROR org.opensearch.dataprepper.pipeline.common.PipelineThreadPoolExecutor - Pipeline [***] process worker encountered a fatal exception, cannot proceed further
java.util.concurrent.ExecutionException: org.opensearch.client.opensearch._types.OpenSearchException: Request failed: [security_exception] no permissions for [cluster:monitor/state] and User [name=***, backend_roles=[***], requestedTenant=null]
```

**To Reproduce**
Create a pipeline with an FGAC-enabled AOS sink and a dynamic index pattern. Don't provide sufficient permissions to the pipeline role to ingest data to AOS. Ingest data into the DataPrepper pipeline to cause a crash.

**Expected behavior**
Similar to the behavior of static indices, DataPrepper should avoid crashing when there is a permissions gap and instead loop while providing helpful messaging to the user so that the issue can be resolved.

**Comment by dlvenable** [comment]
Fixed by #3541.
