### ISSUE TITLE
[BUG] Key value processor will throw NPE if source key does not exist in the Event

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#3496]
**Describe the bug**
The key value processor can throw NPE here (https://github.com/opensearch-project/data-prepper/blob/b4b4a98d10a5cec0d8c0331e7551bc272403c71f/data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessor.java#L239) if the `source` key in the Event does not exist.

**Expected behavior**
Utilize the `tags_on_failure` to tag events that don't have the key, but otherwise will be a no-op and be flushed downstream.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

**Comment by dlvenable** [comment]
Duplicate of #3928.
