### ISSUE TITLE
Opensearch sink: support ingest pipeline config

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/data-prepper#3502]
**Is your feature request related to a problem? Please describe.**
For some use cases ingest pipelines in opensearch are useful. From what I gather from the docs and code the opensearch sink does not support an ingest pipeline option.

**Describe the solution you'd like**
Implement ingest pipeline config option and pass this to opensearch

**Describe alternatives you've considered (Optional)**
Using processors in DP itself, but i.e. filebeat has ingest pipelines that can be used out the box.

**Additional context**
N/A

**Comment by dlvenable** [comment]
@ict-one-nl , What is the difference between this request and #3502?

**Comment by ict-one-nl** [comment]
3502 is this request? :)

**Comment by dlvenable** [comment]
Sorry, I meant #3336.

**Comment by ict-one-nl** [comment]
arf you are right, sorry.
