### ISSUE TITLE
Bulk Operation Retry Strategy should print cause of error

### ISSUE THREAD

**Issue by pcolazurdo** [opensearch-project/data-prepper#3504]
I'm trying to debug an issue in an OS Integration Pipeline, but the only message I get is:

```
WARN  org.opensearch.dataprepper.plugins.sink.opensearch.BulkRetryStrategy - Bulk Operation Failed. Number of retries 5. Retrying... 
```

Which makes impossible to debug the root cause of the issue. It would be very useful to get more information about what was the failure in order to debug issues.

Having a quick look at the code it seems like this [line](https://github.com/opensearch-project/data-prepper/blob/ccbe50c83916e34bde4f8cb0358ea70d9be3488d/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java#L240) is printing the cause if the issue is an exception but there is nothing to print if the error was part of the BulkResponse..

Please note, it is the first time ever I look at this code, so my previous analysis may be wrong, though

**Comment by kkondaka** [comment]
Fixed by PR #3532
