### ISSUE TITLE
[BUG] Docker image jre-jammy contains Berkeley DB

### ISSUE THREAD

**Issue by KarstenSchnitter** [opensearch-project/data-prepper#3543]
**Describe the bug**
The switch to Docker base image "eclipse-temurin:17-jre-jammy" introduced in #3355 adds BerkeleyDB to the image (libdb5.3_5.3.28+dfsg1-0.8ubuntu3_amd64.deb). Berkeley DB is dual license, either Oracle commercial license or GNU AGPL v3 [1]. Both licenses types are problematic for distribution and SaaS deployments.

**To Reproduce**
Either use a package scanning tool e.g Mend or ssh into a running container and use the package tool.

**Environment (please complete the following information):**
 - Version 2.5.0

**Additional context**
The change was introduced by #3355.

[1] https://en.wikipedia.org/wiki/Berkeley_DB#Licensing

**Comment by dlvenable** [comment]
@KarstenSchnitter , Thank you for reporting this. We are looking to move toward Amazon Linux in 2.6.0. I'd appreciate your thoughts on this. Please see #3505.

**Comment by dlvenable** [comment]
This is fixed by #3671 which changes the base image to Amazon Linux 2023.
