### ISSUE TITLE
Improve GRPC request exception logging

### ISSUE THREAD

**Issue by asifsmohammed** [opensearch-project/data-prepper#3621]
**Is your feature request related to a problem? Please describe.**
Right now it's not easy to debug 500 errors in any otel source, if there is an exception which is not an instance of `RequestTimeoutException`, `TimeoutException`, `SizeOverflowException`, `BadRequestException`, `RequestCancelledException`  we increment the `internalServerError` metric. With this metric it's not possible to debug the failures without any logging.

https://github.com/opensearch-project/data-prepper/blob/259fea1ba1ecd0a223499e7c9932457425f08079/data-prepper-plugins/armeria-common/src/main/java/org/opensearch/dataprepper/GrpcRequestExceptionHandler.java#L65

We also return a description with status but looks like the `e.getMessage()` can be null.

https://github.com/opensearch-project/data-prepper/blob/259fea1ba1ecd0a223499e7c9932457425f08079/data-prepper-plugins/armeria-common/src/main/java/org/opensearch/dataprepper/GrpcRequestExceptionHandler.java#L74

**Describe the solution you'd like**
Add a log statement when incrementing the `internalServerError` metric. 
Log should include `getCause` of throwable if `getMessage` of the exception is null.

**Comment by dlvenable** [comment]
I agree with this. With an unknown error like this, we should also log the entire stack trace.

e.g.

```
log.error("Unexpected exception handling request", e);
```
