### ISSUE TITLE
Support more TLS/SSL certificate providers in http source

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#365]
**Is your feature request related to a problem? Please describe.**
Currently only local file certificate provider is supported.

**Describe the solution you'd like**
We will expand support to s3 and ACM when necessary

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by dlvenable** [comment]
This task is highly related to #364. I'd like us to centralize this feature using plugins.
