### ISSUE TITLE
[BUG] ProgressCheck callback silently fails on exception

### ISSUE THREAD

**Issue by engechas** [opensearch-project/data-prepper#3653]
**Describe the bug**
When the call to extend the visibility timeout fails, no exception or logs are thrown. This is because we don't `get` the future for the callback at any point to surface the ExecutionException.

A side effect of this is that the expiry metric for the ack set are not published even though the visibility timeout has expired

Callback invocations:
https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSet.java#L147
https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSet.java#L174

**To Reproduce**
Create an S3-SQS source pipeline with extend visibility timeout enabled. Don't provide the ChangeMessageVisibility permission to the role used for the source.

**Expected behavior**
Failures should be surfaced in the logs and potentially via metrics

**Comment by dlvenable** [comment]
There appear to be two issues here that should be considered.

1. Log the errors and update metrics. This should be done in the S3 source.
2. The acknowledgements expiration may need to be shortened. This requires some additional thought, and probably warrants its own GitHub issue.

**Comment by dlvenable** [comment]
Resolved by #3657.
