### ISSUE TITLE
Not delete output file of File Sink Output on every container/service restart

### ISSUE THREAD

**Issue by canob** [opensearch-project/data-prepper#3687]
Every time that I restart container/service of Data Prepper, the output file configured in my File Sink Output is deleted.

I think that this is a big problem if you are collecting that results file with other program to send it to other platform, because sometimes a file collector do mistakes when the file that is collecting is deleted and a new one with the same name takes its place.

When Data Prepper is working, appends every new line to the file. Is it possible that after a restart of the container/service of Data Prepper, Data Prepper continue appending new lines to the file after restarting, without deleting it first?

Maybe you can add a config option to File Sink Output to decide that.

**Comment by kkondaka** [comment]
Sounds like a good idea to support an option to append to the file instead of truncating the file if it already exists.
