### ISSUE TITLE
[BUG] GHSA-6g3j-p5g6-992f

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#3837]
**Describe the bug**

OpenSearch has a security advisory. It is related to the `_search` API. But, we should update to avoid the CVE.

See advisory:

https://github.com/advisories/GHSA-6g3j-p5g6-992f

**Comment by dlvenable** [comment]
Waiting on the release of OpenSearch 1.3.14.

https://github.com/opensearch-project/opensearch-build/issues/4069

**Comment by sachinkhandelwal** [comment]
For this bug, I couldn't find any commit that provides insight into the fix or any steps to reproduce the issue. If anyone wants to backport the fix, it will be difficult to determine the root cause of the problem.

Please provide the commit that addressed this issue in version 2.11.1.
