### ISSUE TITLE
[BUG] Incomplete route set leads to duplicates when E2E ack is enabled.

### ISSUE THREAD

**Issue by engechas** [opensearch-project/data-prepper#3866]
**Describe the bug**
This is not technically a bug, but is easy to miss and leads to unexpected behavior. If a user has acknowledgements enabled for their source and routes enabled, but the routes do not cover all possibilities of the incoming data, a portion of the data will never end up in a sink or DLQ. This prevents the ack from being acknowledged and the sink permanently loops on a set of incoming data.

Example:
* S3-SQS source pipeline with acks enabled
* A single route is defined where `'/myfield == "my value"'`

If one of the S3 objects contains `/myfield` with a value of `not my value`, then it is not routed to a sink so the acknowledgement set cannot complete successfully. The ack timeout expires and the object re-enters the queue to be processed again.

**To Reproduce**
Steps to reproduce the behavior: Documented above

**Expected behavior**
There are a few ways this could be handled, I am not sure which is correct.

1. Any records not matching a route end up in a DLQ
2. Acknowledgements consider records with no route being dropped as intentional and still send a positive ack in this case
3. Validation prevents a pipeline from being created if acks are enabled and the routes form an incomplete set of all possibilities

**Comment by dlvenable** [comment]
Overall, I think the solution should be proposal 2 - unrouted events are acknowledged. If the user creates a pipeline-level DLQ, then we could route those events there (per proposal 1). The pipeline-level DLQ (#3857) could allow for combining both proposals in this way.

**Comment by kkondaka** [comment]
@dlvenable I am fine with proposal 3. When acks are enabled, we should not silently drop any events to provide durability. What that means is that the config must explicitly drop events, are the data-prepper should not drop just because there is no route.

**Comment by dlvenable** [comment]
We solved this with proposal 2. Un-routed events send acknowledgements.
