### ISSUE TITLE
[BUG] BlockingBuffer.bufferUsage metric does not include records in-flight

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#3936]
**Describe the bug**

The `BlockingBuffer.bufferUsage` metric is inaccurate. It indicates that it is the percentage of the buffer used. However, it is only the percentage of the buffer used for messages that are waiting. It does not include in-flight messages.

**Expected behavior**

I expect this metric to include both the records waiting and the records-in-flight when calculating the usage.

**Screenshots**

We sent these metrics to AWS CloudWatch. You can see in the screenshot below that the sum of `recordsInBuffer` and `recordsInFlight` (the line in blue) reaches near the maximum defined size of 1,000,000 records. However, the `bufferUsage` metric is around 70% at the time that happens. 

![BufferMetrics](https://github.com/opensearch-project/data-prepper/assets/293424/0187b1df-8c44-46de-aafb-a6a52e0dc2b7)

**Additional context**

This can lead to confusion when trying to see why events are not writing to the buffer. The metrics indicate that there is capacity, but we fail to write to the buffer due to a timeout exception.

You can see that below.

https://github.com/opensearch-project/data-prepper/blob/b0d253c810e9ae657a8fd66608a3543296257ab2/data-prepper-plugins/blocking-buffer/src/main/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBuffer.java#L120-L125

This code is what appears to be incorrect. It does not account for the records in-flight.

https://github.com/opensearch-project/data-prepper/blob/b0d253c810e9ae657a8fd66608a3543296257ab2/data-prepper-plugins/blocking-buffer/src/main/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBuffer.java#L202-L205

**Comment by dlvenable** [comment]
An alternative solution is to also update the `recordsInBuffer` metric to more accurately reflect that it is the totality of all records. Then we could have a `recordsWaitingInBuffer`.

Or we could add a new metric that expresses both: `recordsTotalInBuffer`. This would be equal to the sum of both `recordsInBuffer` and `recordsInFlight`.

**Comment by graytaylor0** [comment]
I think there is still value in knowing the number of `recordsInBuffer` from a debugging standpoint

**Comment by kkondaka** [comment]
As discussed offline, I think it is better to have a metric that directly corresponds to the semaphore count that controls the capacity

**Comment by dlvenable** [comment]
I'm thinking of making two changes:

1. Create a new gauge metric on the semaphore's `availablePermits()` to track the actual buffer capacity - `BlockingBuffer.capacityUsed`.
2. Replace the logic for creating the existing `bufferUsage` such that it is effectively `availablePermits() / bufferCapacity`.
