### ISSUE TITLE
[Feature Request] Mapping String to Array

### ISSUE THREAD

**Issue by adplotzk** [opensearch-project/data-prepper#3964]
This is a feature request which is requested a processor to implement the following ETL functionality to handle Mapping string to array.

#SOURCE

             "some_source": [
                    {
                        "src_key_1": "val_1"
                    }
                ]
          
#TO
           
            "some_dest": {
                "dest_key_1": ["val_1"]
            }
                
          
#MAPPING
          
        - from_key: "some_source[]/src_key_1/"
          to_key: "some_dest/dest_key_1[]"
          overwrite_if_to_key_exists: true

**Comment by oeyh** [comment]
This can be achieved with #3867 in combination with `rename_keys` processor.

**Comment by oeyh** [comment]
Closed via #3867
