### ISSUE TITLE
[Feature Request] Dynamic Auto-Map

### ISSUE THREAD

**Issue by adplotzk** [opensearch-project/data-prepper#3965]
{
	      "src_key_0.1": "val_0.1",
	      "src_key_0.2": "val_0.2",
	      "src_key_0.3": "val_0.3",
	      "src_key_0.4": {
		      "src_key_0.5": {
			      "src_key_0.6": "val_0.4"
		      }
	      },
	      "some_source": [
		      {
			      "nested_array": [
				      {
					      "src_key_1": "val_1",
					      "src_key_2": "val_2",
					      "src_key_3": "val_3"
				      },
				      {
					      "src_key_1": "val_5",
					      "src_key_2": "val_6",
					      "src_key_3": "val_7"
				      }
			      ]
		      }
	      ]
      }

#TO

      {
	      "somekey": [
				[
					"src_key_0.1",
					""val_0.1"
				],
				[
					"src_key_0.2",
					""val_0.2"
				],
				[
					"src_key_0.3",
					""val_0.3"
				],
				[
					"src_key_0.4.src_key0.5.src_key0.6",
					"val_0.4"
				],
				[
					"some_source[].nested_array[].src_key_1",
					"val_3, val5"
				],
				[
					"some_source[].nested_array[].src_key_2",
					"val_3, val_6"
				],
				[
					"some_source[].nested_array[].src_key_3",
					"val_3, val_7"
				],
			]
      }

#MAPPING

      - set_default_map_to: "somekey"

**Comment by oeyh** [comment]
Discussed offline. The description has been updated. The transformation involves these steps:
- Flatten the json object. We will end up with bunch of fields on the same level with keys like "key1.key2.key3" or "key4[].key5" (when there are arrays). If multiple values corresponds to the same key, put them in an array
- In the flattened json, if the value is an array, convert it to a string, eg `["value1", "value2"]` --> `"value1, value2"`
- Convert the flattened fields (key-value pairs) to an array, eg `{"key1": "value1", "key2": "value2"}` --> `[["key1", "value1"], ["key2", "value2"]]`

**Comment by oeyh** [comment]
Resolved via #4033, #4075 and #4128
