### ISSUE TITLE
Flaky integration test: Run ./gradlew :data-prepper-plugins:opensearch:test --tests 

### ISSUE THREAD

**Issue by laneholloway** [opensearch-project/data-prepper#398]
**Describe the bug**
This integration test is flaky and goes between passing and not.

**To Reproduce**
1. Create a PR
2. Let the tests run, see it fail
3. Retry the test
4. watch it pass

**Expected behavior**
The tests to run successfully (or not multiple times in a row).

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

**Comment by dlvenable** [comment]
These tests are fairly consistent now, so I'm closing this issue.
