### ISSUE TITLE
[BUG] Upsert action requires existing document in OpenSearch

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#4036]
**Describe the bug**
The `upsert` action is supposed to insert a document if it does not exist, and update a document if it does exist. However, the `upsert` action as part of a bulk request from the `opensearch` sink receives a `document not found` error from OpenSearch.

**To Reproduce**
1. Configure and start a pipeline with an opensearch sink with `action: upsert`
2. Send an Event that does not have an existing `document_id` for that document in the OpenSearch index
3. Observe the error
```
WARN  org.opensearch.dataprepper.plugins.sink.opensearch.BulkRetryStrategy - operation 
= Update, error = [2]: document missing
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

**Comment by dlvenable** [comment]
This is related to #3988. 

@graytaylor0 , Is it a duplicate as well?

**Comment by graytaylor0** [comment]
It is not the same as #3988. #3988 is might be consolidated with #3933 .

However, this one is completely different, and it is strictly focused on upsert not inserting documents when they don't exist
