### ISSUE TITLE
Integrate new Buffer::writeAll API with http source

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#404]
**Is your feature request related to a problem? Please describe.**
Currently http source is still using the Buffer::write API which means incoming request data could be partially written into the Buffer.

**Describe the solution you'd like**
Use the new `Buffer::writeAll` API in http source

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by dlvenable** [comment]
This was completed in Data Prepper 1.2.1.
