### ISSUE TITLE
Support epoch_micro in date processor patterns

### ISSUE THREAD

**Issue by oeyh** [opensearch-project/data-prepper#4076]
**Is your feature request related to a problem? Please describe.**
We do support epoch_second, epoch_mili and epoch_nano, but noticed some users need epoch_micro as well. 

We have a workaround using `value_expression` in `add_entires` to convert micro seconds to other format we support. But we might as well add this `epoch_micro` option to save the need for an additional processor.

**Describe the solution you'd like**
Support epoch_micro in date processor patterns

**Describe alternatives you've considered (Optional)**
Use `value_expression` in `add_entires` to convert micro seconds to other format we support

**Additional context**
N/A

**Comment by Utkarsh-Aga** [comment]
Hello @oeyh 
Can I contribute to this, as this is marked with `good first issue` ? 
If yes, can you let me know the process for contribution ?

**Comment by oeyh** [comment]
@Utkarsh-Aga Absolutely. Thank you for willing to do this! 
Please refer to this [guideline](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md) for the process to open pull requests. Also you may find this [developer guide](https://github.com/opensearch-project/data-prepper/blob/main/docs/developer_guide.md) helpful.

**Comment by Utkarsh-Aga** [comment]
Sure, Thanks a lot :)
