### ISSUE TITLE
Improve or Clarify Backpressure on OTel-Grpc-Sources

### ISSUE THREAD

**Issue by KarstenSchnitter** [opensearch-project/data-prepper#4119]
**Is your feature request related to a problem? Please describe.**
Ingestion of events via Opentelemetry over GRPC can fail due to a full buffer or an open CircuitBreaker.
In that case, an error response is sent. When testing with the OpenTelemetry Collector, this leads to dropped data by the collector.
Reason for this is, that apparently the [OTLP/gRPC Throttling specification](https://opentelemetry.io/docs/specs/otlp/#otlpgrpc-throttling) is not used properly. The DataPrepper gRPC response needs to contain a proper `RetryInfo`.

**Describe the solution you'd like**
DataPrepper should implement proper OTLP/gRPC throttling, when the ingress buffers are full or the circuit breaker is open.

**Describe alternatives you've considered (Optional)**
DataPrepper can document, that on full buffers or open circuit breakers, requests are rejected as non-retryable. This can happen for both cases or separately just for one, e.g. open circuit breaker.

**Additional context**
Currently on an open curcuit breaker, the error message from the [CircuitBreakingBuffer](https://github.com/opensearch-project/data-prepper/blob/3da1696aa1ac3b8d12c3c8960c21bbda722474d2/data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/CircuitBreakingBuffer.java#L62) is contained in the DataPrepper response.
This is managed by the [GrpcRequestExceptionHandler](https://github.com/opensearch-project/data-prepper/blob/3da1696aa1ac3b8d12c3c8960c21bbda722474d2/data-prepper-plugins/armeria-common/src/main/java/org/opensearch/dataprepper/GrpcRequestExceptionHandler.java#L56), that generates a `RESOURCE_EXHAUSTED`response status. This is only retryable, if a `RetryInfo` is present according to <https://opentelemetry.io/docs/specs/otlp/#failures>. This is currently not the case, hence the OpenTelemetry collector drops the events and does no retries.

**Comment by dlvenable** [comment]
@KarstenSchnitter , For both a full buffer and the circuit breaker, we can tell the client that the request can be retried. 

What I'm unsure of is what time we can give back to the client. One option would be to use the request timeout. Perhaps there is something we can get from the buffer to hint at the time. But, I'm not sure.

**Comment by dlvenable** [comment]
@KarstenSchnitter , That approach sounds reasonable. And we could allow for configuration of the initial retry and the maximum.
