### ISSUE TITLE
Add `long` as a target type for `convert_entry_type` processor

### ISSUE THREAD

**Issue by Utkarsh-Aga** [opensearch-project/data-prepper#4120]
**Is your feature request related to a problem? Please describe.**
Currently, `date` processor parses the timestamp and stores in `destination` field which is of `String` type. 

**Describe the solution you'd like**
In scenario's, when the integer value of `destination` field is needed, we could use this `convert_entry_type` processor to convert the `destination` field to `long`, because using `integer` is not feasible for `epoch` times.

**Comment by Utkarsh-Aga** [comment]
If the team is okay to have this feature, then I would be more than happy take a shot at it and raise a PR.

**Comment by dlvenable** [comment]
@Utkarsh-Aga , I agree with you. Being able to convert to a `long` makes sense and is needed at certain times. We'd be happy to review and accept a PR. I'll assign this to you.

**Comment by Utkarsh-Aga** [comment]
Sure, Thank you.
