### ISSUE TITLE
[BUG] S3 Scan has potential to filter out objects with the same timestamp

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#4123]
**Describe the bug**
Scheduled S3 Scan filters out objects by checking a global state item that contains the timestamp of the most recent object that was processed during the previous scan. (https://github.com/opensearch-project/data-prepper/blob/503b7741fe63596ad994198e513404c1143f9e1d/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanPartitionCreationSupplier.java#L168)

This has the potential to skip objects that are missed in the scan, but created with the same timestamp.

**Expected behavior**
Do not filter out objects that have a timestamp equal to the last modified timestamp

**Additional context**

**Comment by jw-amazon** [comment]
To work around the bug, do we have to keep the timestamp of the objects different when dropping the objects into s3 ingest folder?
