### ISSUE TITLE
Support reading of old image for delete events on DynamoDB source

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#4261]
**Is your feature request related to a problem? Please describe.**
As a user of the DynamoDB source using a custom `document_id` or `document_version` from my DynamoDB items, I am not able to keep deletions on my DDB table in sync with OpenSearch, because Data Prepper only reads the `newImage` of DDB stream records, and does not write the old image

**Describe the solution you'd like**
A new parameter under the `stream` block of DDB source

```
source:
  dynamodb:
    stream:
      use_old_image_for_deletes: true
```

When this is set to true, Data Prepper would check stream records for the REMOVE action, and then it would construct the Event from the old image, rather than the new empty image. 

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by dlvenable** [comment]
We changed this to `view_on_remove: OLD_IMAGE` to potentially support other configurations. See the following thread:

https://github.com/opensearch-project/data-prepper/pull/4275#discussion_r1523344084
