### ISSUE TITLE
[BUG] Empty DLQ entries when version conflicts occur

### ISSUE THREAD

**Issue by engechas** [opensearch-project/data-prepper#4301]
**Describe the bug**
An empty DLQ object is created when there are failures shipping to OpenSearch but all of the failures are due to a version conflict. The code here filters out version conflicts from the DLQ entries: https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java#L353-L356

But then there is no empty check before sending the doc list to the DLQ: https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java#L369

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

**Comment by amitkirdatt** [comment]
Told by AWS Support that this issue is related to the issue that I opened here: https://github.com/opensearch-project/data-prepper/issues/4304
