### ISSUE TITLE
[BUG]  2024-04-17T14:11:41,339 [pool-6-thread-1] WARN    org.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-host-1, groupId=host] Connection to node -1 (kafka.data-prepper/172.27.91.183:9092) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.

### ISSUE THREAD

**Issue by hunter-luo666** [opensearch-project/data-prepper#4431]
**Describe the bug**

aws msk(no auth/ disabled TLS) --> data prepper --> aws opensearch

when deployed data prepper:
2024-04-17T14:11:41,339 [pool-6-thread-1] WARN    org.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-host-1, groupId=host] Connection to node -1 (kafka.data-prepper/172.27.91.183:9092) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.

`

data:
  pipelines.yaml: |
    log-pipeline:
      source:
        kafka:
          bootstrap_servers:
            - b-1xxxxxxx:9092
          topics:
            - name: "host-test"
              group_id: "host"
              serde_format: "plaintext"  
            - name: "kube-test"
              group_id: "kube"
              serde_format: "plaintext"  
      sink:
        - opensearch:
            hosts: [ "https://vpc-devops-xxxxxx-xxxxast-1.es.amazonaws.com" ]
            username: "admin"
            password: "KfExxxxxxxxxxxxxc"
            index: sample_app_logs
  data-prepper-config.yaml: |
    ssl: false
`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

**Comment by KarstenSchnitter** [comment]
Thanks for filing the issue. Can you add your Kafka version? The error indicates a version older than 1.0.0 but I doubt that. It might just be an unknown version to the Kafka client used in DataPrepper.

**Comment by hunter-luo666** [comment]
resolved
added ：
          encryption:
            type: "none"
            insecure: true
           
           please update document ：https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sources/kafka/#encryption
           should use insecure instead of Insecure          
<img width="858" alt="image" src="https://github.com/opensearch-project/data-prepper/assets/157451356/8bc3b728-06c4-45b1-8b97-86e7939f06e0">
