### ISSUE TITLE
Support conditional expression to evaluate based on the data type for a given field

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#4478]
## Background

Some processors we only want to run when the field has a certain type.

## Proposal

I propose creating a new operator within the Data Prepper expression language: `typeof`.

This could be used to determine if a given field has a certain type.

For example:

```
/myfield typeof string
```

Additionally, this approach could support inheritance.

For example, the following could be true:

```
25 typeof integer
25 typeof number
25.5 typeof double
25.5 typeof number
```

### Types

Data Prepper doesn't have have a consistent concept of types. However, we should have some core types. We can base these on what we already have for the convert entries processor.

https://github.com/opensearch-project/data-prepper/blob/24bbbf1576849f38671b9e4a03de347c9e89c28f/data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/TargetType.java#L21-L25

## Alternative

One alternative is to add a new function.

```
$type(/myfield) == 'string'
```

However, this would not work so well with inheritance.

**Comment by kkondaka** [comment]
Another option is to provide a function in expressions like `isType(/field, "string")` or `isTypeOf(/field, "string")`.

**Comment by dlvenable** [comment]
Completed by: #4500
