### ISSUE TITLE
Resolve approach for JSON path and dots in key names

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#450]
**Is your feature request related to a problem? Please describe.**

How do we want to support both of these requirements:
* Providing a JSON-path structure for accessing fields within events
* Allowing fields to contain dots in the name e.g. `my.field`.

Raised by this question:
https://github.com/opensearch-project/data-prepper/pull/435/files#r732111116

**Comment by laneholloway** [comment]
Do we properly handle accessing an item in an array? e.g. `foo.bar[5] = "f"`
```
{
  "foo": {
    "bar": ["a", "b", "c", "d", "e", "f"]
  }
}
```

**Comment by cmanning09** [comment]
> Do we properly handle accessing an item in an array? e.g. `foo.bar[5] = "f"`
> 
> ```
> {
>   "foo": {
>     "bar": ["a", "b", "c", "d", "e", "f"]
>   }
> }
> ```

Not at this moment, but it is a good point and something we should consider when making this decision.
