### ISSUE TITLE
[RFC] Logstash Configuration Converter

### ISSUE THREAD

**Issue by sshivanii** [opensearch-project/data-prepper#452]
### What kind of business use case are you trying to solve? What are your requirements?

We want to provide Logstash users an easy way to run their workloads on Data Prepper. By leveraging their existing Logstash configuration file, we will make the transition from Logstash to Data Prepper as seamless as possible.

### What is the problem? What is preventing you from meeting the requirements? 

The Pipeline Configuration file required to run a Data Prepper instance (`pipelines.yaml`) is in YAML format and Logstash configuration file is a custom format. 

### What are you proposing? What do you suggest we do to solve the problem or improve the existing situation? 

The goal is to take existing Logstash configuration files, transform them into Data Prepper configuration files and build a Data Prepper Log Ingestion pipeline from them. The Logstash Configuration Converter will support the following requirements:

* The Converter will transform the Logstash configuration format to a Data Prepper YAML with the respective mapping and run alongside the Data Prepper log pipeline. This will be a 1-step process to make it user-friendly.
* The Converter will fail for unsupported Logstash plugins and Conditionals (scope is mentioned below in **What are your assumptions or prerequisites?** section). However, if the basic supported plugins are present in the Configuration, it will process those and throw errors for the Unsupported plugins. This can be altered later on when we extend the scope.

### macOS/Linux

* User has a `logstash.conf`file.
* As of Data Prepper 1.2 release, the Converter will be part of the Data Prepper uber-jar.
* User will run the uber-jar with the Logstash configuration file and `data-prepper-config.yaml` (to configure Data Prepper server with TLS/SSL):
```
java -jar data-prepper-core-$VERSION.jar logstash.conf data-prepper-config.yaml
```
* The `logstash.yaml` will be generated.
* The Data Prepper log pipeline will read the `logstash.yaml` and run the plugins.

### Docker

* User can pull the Data Prepper for Docker image using:
```
docker pull opensearchproject/data-prepper:latest
```
* A bind-mounted volume can be used to give the Logstash configuration using:

```
docker run --name data-prepper --expose 21890 
-v /full/path/to/logstash.conf:/usr/share/data-prepper/pipelines.conf 
-v /full/path/to/data-prepper-config.yaml:/usr/share/data-prepper/data-prepper-config.yaml 
opensearchproject/opensearch-data-prepper:latest pipelines.conf
```

### What are your assumptions or prerequisites? 

* Users wish to use existing Logstash configuration with Data prepper.
* Scope of the Converter for the Data Prepper 1.2 release will be supporting a Log HTTP Source plugin as Input plugin, Grok Prepper as Filter Plugin and Opensearch Sink as Output plugin.
* Conditionals and other Logstash plugins are not supported in this Converter for the Data Prepper 1.2 release.

**Comment by dlvenable** [comment]
This flow diagram outlines the proposed approach for translating Logstash configuration files into Data Prepper configuration files.

![LogstashConfigurationFlow](https://user-images.githubusercontent.com/293424/141012759-d90ac196-36d8-4c5d-9d11-3773509e6c6d.png)

**Comment by sshivanii** [comment]
Closing this RFC since implementation is complete.
