### ISSUE TITLE
Use default role in secrets manager configuration if it exists

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#4567]
**Is your feature request related to a problem? Please describe.**
A default role can now be configured in the data-prepper-config.yaml (https://github.com/opensearch-project/data-prepper/pull/4559) for all plugins that use `AwsCredentialsSupplier` to get credentials. This includes all plugins but the secret manager plugin, since the secret manager plugin is an additional extension that is decoupled from using `AwsCredentialsSupplier`

**Describe the solution you'd like**
A way to use the default role for secrets manager configuration

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by dlvenable** [comment]
Most of this work would need to be done in #2825. I'll close this as a duplicate.
