### ISSUE TITLE
[BUG] Parameters in the index name for OpenSearch sink are not working as documented

### ISSUE THREAD

**Issue by Jon-AtAWS** [opensearch-project/data-prepper#4568]
**Describe the bug**
I had a running Amazon OpenSearch Ingestion pipeline and change the config from

```"index": "cloudtrail"```

to

```"index": "cloudtrail-${yyyy.MM.dd}"```

As documented here: https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sinks/opensearch/

"The name of the export index. Only required when the index_type is custom. The index can be a plain string, such as my-index-name, contain [Java date-time patterns](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html), such as my-index-${yyyy.MM.dd} or my-${yyyy-MM-dd-HH}-index"

I see errors in CloudWatch Logs like this:

```2024-05-26T18:14:07.600 [log-pipeline-sink-worker-2-thread-1] ERROR org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink - There was an exception when constructing the index name. Check the dlq if configured to see details about the affected Event: The key yyyy.MM.dd could not be found in the Event when formatting```

My problem may be that I didn't set index_type. But the docs specify that default index_type is `custom`. I'll try that next.

"Tells the sink plugin what type of data it is handling. Valid values are custom, trace-analytics-raw, trace-analytics-service-map, or management-disabled. Default is custom."

**To Reproduce**

Create a data prepper config with a sink like this:

```
    "sink": [
      {
        "opensearch": {
          "hosts": [
            "https://<hostname>"
          ],
          "index": "cloudtrail-${yyyy.MM.dd}",
          "aws": {
            "sts_role_arn": "<role arn>",
            "region": "us-west-2",
            "serverless": false,
            "max_retries": 10
          }
        }
      }
    ]
```

and send data. You should see the error in the data prepper logs. If not, create an OpenSearch Ingestion pipe and try the above sink.

**Expected behavior**

I should see data in an index named 'cloudtrail-2024.05.26", e.g.

I would like a way to specify a time zone so that indices roll over in my local time zone. I don't see that in the parameters for the sink. I assume indices will be named based on UTC instead.

**Environment (please complete the following information):**
 - OS: Amazon OpenSearch Ingestion

**Comment by Jon-AtAWS** [comment]
Update:

```
          "index": "cloudtrail-${yyyy.MM.dd}",
          "index_type": "custom",
```

Does not change the behavior.

Am I supposed to use `normalize_index`?

**Comment by Jon-AtAWS** [comment]
This is solved. The documentation is wrong, you need to use a % sign instead of a $ sign...

```"index": "cloudtrail-%{yyyy.MM.dd}"```

Does the right thing. 

Can someone move this to the documentation repo?

**Comment by Utkarsh-Aga** [comment]
Hello @Jon-AtAWS, I was opening the PR to address another [issue](https://github.com/opensearch-project/documentation-website/issues/7250), saw this one and have combined that PR to address this one also. Please let me know if that is fine or require any additional changes.

**Comment by Jon-AtAWS** [comment]
Hi @Utkarsh-Aga - yes, that's fine to consolidate changes to one issue.
