### ISSUE TITLE
[FEATURE] Set `data-prepper` plugin 3.0.0 baseline JDK version to JDK-21

### ISSUE THREAD

**Issue by reta** [opensearch-project/data-prepper#4605]
### Is your feature request related to a problem? Please describe

Set `data-prepper` plugin 3.0.0 baseline JDK version to JDK-21

### Describe the solution you'd like

See please https://github.com/opensearch-project/OpenSearch/issues/10745

### Related component

Build

### Describe alternatives you've considered

N/A

### Additional context

See please https://github.com/opensearch-project/OpenSearch/issues/14011

**Comment by dlvenable** [comment]
Data Prepper runs and deploys independently of OpenSearch. We have an issue to track JDK changes to at least 17 which we are tracking in #3192.

I'm going to close this since OpenSearch doesn't need to depend on data-prepper making this change.

**Comment by reta** [comment]
@dlvenable thanks for confirming, afaik the `data-prepper` relies on OpenSearch bits (specifically RHCL), the artifacts as of 3.0.0 would require JDK-21.

**Comment by dlvenable** [comment]
@reta , Thanks for pointing that out. We would like to get to the point where we only use `opensearch-java`, but I suspect that will not be in time.
