### ISSUE TITLE
Provide demo TLS/SSL cert and key for otel-trace-source

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#462]
**Is your feature request related to a problem? Please describe.**
Currently ssl is enabled by default in otel-trace-source but we require user to provide sslCertificateFile and sslKeyFile in order to run the source.

**Describe the solution you'd like**
We could default sslCertificateFile and sslKeyFile to use demo-data-prepper.crt and demo-data-prepper.key respectively in https://github.com/opensearch-project/data-prepper/tree/main/examples/demo

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by dlvenable** [comment]
Similar to #461, Data Prepper will not use TLS or authentication by default on the OTel input plugin. Users must add this input to their pipelines - they are not active by default. Data Prepper will include documentation and warnings - see #521 .
