### ISSUE TITLE
parse_json: add ability to only parse top level fields

### ISSUE THREAD

**Issue by cameronattard** [opensearch-project/data-prepper#4695]
**Is your feature request related to a problem? Please describe.**
Nested json parsing can introduce challenges with OpenSearch field limits and type conflicts between object and concrete field types. It would be helpful to be able to only parse the top level of JSON fields, leaving subfields as strings.

**Describe the solution you'd like**
Add an option to only parse the top level of a JSON-encoded string field.

**Describe alternatives you've considered (Optional)**
Perform JSON parsing elsewhere, e.g. fluent-bit.

**Additional context**
N/A

**Comment by dlvenable** [comment]
This is a good idea. I think we can generalize this to supporting a configurable depth. In your case, you'd want a depth of `1`.

@cameronattard , Would you be interested in contributing this as a solution? I'd be happy to help get you started on what needs to change.

**Comment by cameronattard** [comment]
> This is a good idea. I think we can generalize this to supporting a configurable depth. In your case, you'd want a depth of `1`.
> 
> @cameronattard , Would you be interested in contributing this as a solution? I'd be happy to help get you started on what needs to change.

Unfortunately I don't think I'll be able to make time to do it any time soon.
