### ISSUE TITLE
[BUG] Cannot add conditionals to grok processor

### ISSUE THREAD

**Issue by NeRX322** [opensearch-project/data-prepper#4767]
**Describe the bug**
I add conditional grok processor from the documentation to my dataprepper pipeline and i get error 

at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 72 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: while parsing a block mapping
 in 'reader', line 17, column 10:
             grok_when: '/type == "ipv4"'
             ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 18, column 12:
               match:
               ^
 
reference: https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/grok/#conditional-grok

**To Reproduce**

1. Go to dataprepper yml pipeline
2. Add https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/grok/#conditional-grok
3. Restart dataprepper

**Expected behavior**
Dataprepper is running, conditions work

**Environment (please complete the following information):**
 - OS: RHEL 8
 - Version: 2.8.0
 
<img width="610" alt="123123" src="https://github.com/user-attachments/assets/5df52c17-0072-430a-a719-222faaf35e11">

**Comment by dlvenable** [comment]
@NeRX322 , The `match` option is an option for `grok`, not for `grok_when`. So you need to remove some extra spaces on it.

Please compare to the formatting below.

```
processor:
  - grok:
      grok_when: '/type =="ipv4"'
      match:
        message: [...]
```

**Comment by NeRX322** [comment]
@dlvenable ye, that works, i found multiple documentation errors, where can i contribute and fix doc errors that i found in DataPrepper? I'm more willing to do that

**Comment by dlvenable** [comment]
@NeRX322 , Thank you for taking note of this. You can make contributions in the form of PRs in the documentation-website project.

The Data Prepper documentation is located in:

https://github.com/opensearch-project/documentation-website/tree/main/_data-prepper

Please see the documentation project's [CONTRIBUTING guidelines](https://github.com/opensearch-project/documentation-website/blob/main/CONTRIBUTING.md) as well.
