### ISSUE TITLE
[BUG] Close Opensearch RestHighLevelClient in OpenSearchClientRefresher on shutdown and initialization failure

### ISSUE THREAD

**Issue by dinujoh** [opensearch-project/data-prepper#4770]
**Describe the bug**
When the data prepper pipeline Opensearch Sink initialization fails, data prepper continuously retries to recreate Opensearch client and OpenSearchClientRefresher (refresh credentials). Looks like on initialization failure, we only close Opensearch client and not OpenSearchClientRefresher (this has another reference to Opensearch client). These unclosed Opensearch clients are consuming threads and are resulting in OOM. 

**To Reproduce**
If the Opensearch Sink credentials or data/network access policy is not configured correctly, data prepper continuously retries to recreate Opensearch client. Below OOM exception is seen in the logs.

```
 ERROR org.opensearch.dataprepper.pipeline.common.PipelineThreadPoolExecutor - Pipeline [cdc-pipeline] process worker encountered a fatal exception, cannot proceed further
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
```

**Expected behavior**
The Opensearch Sink/Source should gracefully close the opened connection.

**Code Reference**
Should add close method to [OpenSearchClientRefresher](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchClientRefresher.java) to close OpenSearchClient and call it [here](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java#L589).

**Comment by dinujoh** [comment]
https://github.com/opensearch-project/data-prepper/pull/4758

**Comment by dlvenable** [comment]
@dinujoh , Do you think that #4758 will resolve this? Is there anything missing that you see?
