### ISSUE TITLE
[BUG] DynamoDB Leader Thread can crash if it fails to save state for the leader partition

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#4775]
**Describe the bug**
DynamoDB pipelines leader thread can crash and exit if an error is thrown on this line trying to update state. While this should not happen very often, if there is a 5xx error the source coordination store, it results in this thread crashing and this will block discovery of new dynamodb stream shards.

**Expected behavior**
Handle exceptions properly in this thread and continue running shard discovery if a `PartitionUpdateException` is thrown.

**Additional context**

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/krisfreedain), [3](https://github.com/andrross)
