### ISSUE TITLE
Add ReplaceStringProcessor for simple string substitution that doesn't involve regex

### ISSUE THREAD

**Issue by dinujoh** [opensearch-project/data-prepper#4953]
**Is your feature request related to a problem? Please describe.**
It would be nice to have ReplaceStringProcessor that use Java `String.replace()` method that is highly optimized for simple string replacements. It uses a more efficient algorithm than the `Matcher.replaceAll()` method used in [SubstituteStringProcessor](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/SubstituteStringProcessor.java#L57)

**Describe the solution you'd like**
ReplaceStringProcessor implementation

```
final String newValue = value.replace(entry.getFrom(), entry.getTo());
recordEvent.put(entry.getSource(), newValue);
```

**Comment by oeyh** [comment]
Resolved by #4954
