### ISSUE TITLE
The `processor` documentation is missing sub-documentation for `otel_trace_raw` and `service_map_stateful`

### ISSUE THREAD

**Issue by linghengqian** [opensearch-project/data-prepper#4976]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. It would be nice to have [...]

- No.

**Describe the solution you'd like**

- The `processor` documentation is missing sub-documentation for `otel_trace_raw` and `service_map_stateful`. I hope the documentation can add some explanation.
- In https://opensearch.org/docs/latest/data-prepper/common-use-cases/trace-analytics/#processor, it is mentioned that there are `processors` named `service_map_stateful` and `otel_traces_raw`.
- ![image](https://github.com/user-attachments/assets/100b0085-f81a-49b7-9106-1f8053287a88)
- Interestingly, https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/processors/ does not mention the existence of `service_map_stateful` and `otel_traces_raw` at all.
- ![image](https://github.com/user-attachments/assets/8bdd6e22-217e-4950-9ee5-aeb558149370)

**Describe alternatives you've considered (Optional)**

- Null.

**Additional context**

- Null.

**Comment by dlvenable** [comment]
@linghengqian , The `otel_trace_raw` is the deprecated name for `otel_traces`. See https://github.com/opensearch-project/data-prepper/blob/db9a849b388780c151942931ea6c64350c00c185/data-prepper-plugins/otel-trace-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/oteltrace/OTelTraceRawProcessor.java#L39.

The same is true of `service_map_stateful`.

Would you be interested in updating the documentation with information on these?

**Comment by linghengqian** [comment]
> Would you be interested in updating the documentation with information on these?

- I opened #5017 to update the documentation and example.
