### ISSUE TITLE
Official Docker images for ARM64

### ISSUE THREAD

**Issue by riconnon** [opensearch-project/data-prepper#4981]
**Is your feature request related to a problem? Please describe.**
Since both OpenSearch and OpenSearch-Dashboards official docker images have ARM64 variants it would be nice if data-prepper did too

**Describe the solution you'd like**
Ideally official builds would push a multi-architecture manifest containing both amd64 and arm64 variants to Docker Hub

**Comment by KarstenSchnitter** [comment]
Thanks for raising the issue. I am affected by this as well.

**Comment by dlvenable** [comment]
@riconnon , Thank you for the interest. We have #640 open for this issue. I'll close this one in favor of that.
