### ISSUE TITLE
Support OpenTelemetry logs in S3 source

### ISSUE THREAD

**Issue by danhli** [opensearch-project/data-prepper#5028]
**Is your feature request related to a problem? Please describe.**
It would be nice to provide native support for OTLP JSON logs in [S3 source](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sources/s3/). OTLP JSON logs confirms to the [OTLP specification](https://opentelemetry.io/docs/specs/otlp/) and are stored as JSON files ([sample file](https://github.com/open-telemetry/opentelemetry-proto/blob/main/examples/logs.json)). When the original log messages are in JSON format, the OTel collector would store the log messages in escaped JSON format under logRecords/body/stringValue. 

For example:
"logRecords":&nbsp;[
&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;"body":&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"stringValue":&nbsp;"{\\"key1\\":\\"val1\\",\\"key2\\":\\"val2\\"}"
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;}
]
 

The log format is currently supported in [otel_logs_source](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sources/otel-logs-source/) when the OTel JSON logs are ingested through http endpoints. However, if the OTLP JSON logs are stored in files in a S3 bucket, there isn't a way to parse the escaped JSON. 

**Describe the solution you'd like**
Add a new codec option `otel_logs` in the [S3 source](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sources/s3/) configuration. With the following pipeline configuration, the OTLP JSON logs will be ingested into OpenSearch with one document per log record and all the fields in the original log messages, e.g. key1, key2, and the attributes will be stored in separate document. 

For example:
version : "2"
s3-log-pipeline:
&nbsp;&nbsp;source:
&nbsp;&nbsp;&nbsp;&nbsp;s3:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;acknowledgments : true
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;notification_type : "sqs"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;compression : "none"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;codec:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;otel_logs:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;format: "json"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;workers : 3
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sqs:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;queue_url : ""
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;maximum_messages : 10
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;visibility_timeout : "60s"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;visibility_duplication_protection : true
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aws:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region : "us-west-2"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sts_role_arn : ""
&nbsp;&nbsp;processor:
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;parse_json:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source : "/body"
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;delete_entries:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;with_keys : ["body"] 

**Expected result**
- Each log record is stored in a separate document in an OpenSearch index
- Each document contains all the attributes that are shared by all the log records, i.e. the attributes under resourceLogs/resource

For example: 
{
&nbsp;&nbsp;"_index": "my-index",
&nbsp;&nbsp;"_id": "qyamVZIBXzpFSvHE1m14",
&nbsp;&nbsp;"_score": 1,
&nbsp;&nbsp;"_source": {
&nbsp;&nbsp;&nbsp;&nbsp;"traceId": "",
&nbsp;&nbsp;&nbsp;&nbsp;"spanId": "",
&nbsp;&nbsp;&nbsp;&nbsp;"schemaUrl": "https://opentelemetry.io/schemas/1.6.1",
&nbsp;&nbsp;&nbsp;&nbsp;"key1": "val1",
&nbsp;&nbsp;&nbsp;&nbsp;"key2": "val2",
&nbsp;&nbsp;&nbsp;&nbsp;"key3": "ke3",
&nbsp;&nbsp;&nbsp;&nbsp;"resource.attributes.service.name": "my.service"
&nbsp;&nbsp;}
}

**Comment by dlvenable** [comment]
We took the approach of implementing this as:

```
codec:
  otel_logs:
    format: json
```

This will allow us to also support a binary version in the future.

```
codec:
  otel_logs:
    format: binary
```
