### ISSUE TITLE
Support for reading CloudWatch Logs JSON using json codec

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#5045]
**Is your feature request related to a problem? Please describe.**

We want to be able to decode CloudWatch Logs subscription filters.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters.html

```
{
    "owner": "111111111111",
    "logGroup": "CloudTrail/logs",
    "logStream": "111111111111_CloudTrail/logs_us-east-1",
    "subscriptionFilters": [
        "Destination"
    ],
    "messageType": "DATA_MESSAGE",
    "logEvents": [
        {
            "id": "31953106606966983378809025079804211143289615424298221568",
            "timestamp": 1432826855000,
            "message": "{\"eventVersion\":\"1.03\",\"userIdentity\":{\"type\":\"Root\"}"
        },
        {
            "id": "31953106606966983378809025079804211143289615424298221569",
            "timestamp": 1432826855000,
            "message": "{\"eventVersion\":\"1.03\",\"userIdentity\":{\"type\":\"Root\"}"
        },
        {
            "id": "31953106606966983378809025079804211143289615424298221570",
            "timestamp": 1432826855000,
            "message": "{\"eventVersion\":\"1.03\",\"userIdentity\":{\"type\":\"Root\"}"
        }
    ]
}
```

There are a few things the existing `json` codec will have trouble with here.

1. It picks the first JSON array. In this case it will be `subscriptionFilters` rather than `logEvents`.
2. There is useful metadata that never appears in the generated events. For example, `logStream`.

**Describe the solution you'd like**

I'd like the existing `json` codec to support a few new features.

1. Allow the pipeline author to choose the key within the JSON to parse.

```
codec:
  json:
    key_name: logEvents
```

The `key_name` matches the `json` output codec's similar configuration.

https://github.com/opensearch-project/data-prepper/blob/76d76fc19a4cde6031195663b5d6375655fe53aa/data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/codec/json/JsonOutputCodecConfig.java#L13-L15

2. Allow selecting data from the root of the JSON to include in each object.

```
codec:
  json:
    include_keys: ['owner', logGroup', 'logStream' ]
```

This would output events like the following:

```
{
  "id": "31953106606966983378809025079804211143289615424298221568",
  "timestamp": 1432826855000,
  "message": "{\"eventVersion\":\"1.03\",\"userIdentity\":{\"type\":\"Root\"}",
  "owner": "111111111111",
  "logGroup": "CloudTrail/logs",
  "logStream": "111111111111_CloudTrail/logs_us-east-1",
}
```

3. Allow selecting data from the root of the JSON to include in the metadata for each object.

```
codec:
  json:
    include_keys_metadata: ['owner', logGroup', 'logStream' ]
```

**Comment by sb2k16** [comment]
I would like to work on this issue. Could you please assign this to me.
