### ISSUE TITLE
Support parsing messages with key-value strings such as queries and properties

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#507]
Data Prepper should have a processor which can parse key-value strings from one field and save the results into another field as a map.

For example, on the input event:

```
{
  "query": "key1:value1&key2:value2&key3:value3"
}
```

Could update the event to include a field:

```
{
  "query_params" : {
    "key1" : "value1",
    "key2" : "value2",
    "key3" : "value3"
  }
}
```

This processor must allow configuration of:

* The source field (`query` in the example above)
* The destination field (`query_params` in the example above)
* The delimiter between fields (`&` in the example above)
* The delimiter between key and value (`:` in the example above)
* non_match value - default `null`, the value to assign a key when it has no match
* prefix - A prefix to all keys. default `""`. 

It should also support regex expressions for both types of delimiters.

**Comment by dapowers87** [comment]
I searched GitHub for Logstash configuration files that use the kv filter. There were roughly 545 instances found. The most popular configuration options were:

- source
- field_split
- prefix
- target
- value_split
- field_split_pattern

Less popular configuration options were:

- tag_on_failure
- trim_key
- trim_value
- include_keys
- remove_char_key
- recursive
- remove_char_value
- allow_duplicate_values
- exclude_keys
- include_brackets
- transform_key
- whitespace
- default_keys
- tag_on_timeout
- timeout_millis
- ecs_compatibility
- value_split_pattern

I plan to implement the following existing configuration options:

- source
  - The default value would be `message`, any non-null string would be allowed
- target (I refer to it as `destination`)
  - The default value would be `parsed_message`, any non-null string would be allowed
- field_split_pattern (I refer to it as `field_delimiter_regex`)
  - The default value would be `&`, any non-null regex string would be allowed
- value_split_pattern (I refer to it as `key_value_delimiter_regex`)
  - The default value would be `:`, any non-null regex string would be allowed
- allow_duplicate_values
  - The default value would be `true`, any boolean would be allowed
- prefix
  - The default value would be an empty string, any non-null string would be allowed
 
I also plan on implementing a configuration option called non_match_value, which defines the value to be used when a key/value split fails.
- The default value would be `null`, any string or `null` would be allowed

**Comment by graytaylor0** [comment]
@dapowers87 Some other configurations to consider are from Cargill (https://github.com/Cargill/OpenSIEM-Logstash-Parsing/search?q=kv). I see things like `trim_key` used in these a couple times. The user will probably want some way to ignore certain characters so things like 

```
key1=value1 & key2=value2&    key3=value3
``` 

don't actually add those spaces to the keys or values. If they don't have that then we should make sure they understand how the processor works, and that they will have to use another processor to `trim_keys` or manipulate the keys and values (could be in either `mutate` or the `string_manipulation` processor.

**Comment by dlvenable** [comment]
Thanks @dapowers87 for putting this together.

Regarding the names, I'd like us to be consistent. So if we use `target` or `destination` here, I think we'd want to use that for copy or move in #508.

I think the default behavior should support a known and common scenario. A good one would be supporting HTTP query strings. So I'd like the default `key_value_delimiter_regex` to be a `=`. (Sorry that my initial example was somewhat unhelpful in this regard).

**Comment by dinujoh** [comment]
@dapowers87 Regarding non_match_value, do we have a use case to retain original value in target/destination ? I see default value is null. If we have use case we should have default value as original value and non_match_value can be nullable field.

**Comment by dapowers87** [comment]
> @dapowers87 Regarding non_match_value, do we have a use case to retain original value in target/destination ? I see default value is null. If we have use case we should have default value as original value and non_match_value can be nullable field.

We are not able to get the original value as the split failed. For example, if the `key_value_delimiter_regex` were `=` and the message were `{"message":"key1value1&key2=value2"}`, the proposed output would be `{"key1value1": null, "key2": "value2"}`

**Comment by dlvenable** [comment]
I think that proposed approach is good. It would work for an HTTP query string like:

```
pretty&q=mysearch
```

Then we let the pipeline author decided what it is. They could set `non_match_value=true` which would be result in:

```
{"pretty":true, "q": "mysearch"}
```

**Comment by dapowers87** [comment]
In Logstash, there is a `field_split` and a separate `field_split_pattern`. `field_split` is used about three times as often as `field_split_pattern` on GitHub. 

`field_split` splits on an array of characters (e.g. `&?` would split on either `&` or `?`). Special regex characters such as `[` or `]` need a `\` to escape it. 

`field_split_pattern` splits on a regex expression. Special regex characters such as `[` or `]` need a `\\` to escape it.

The question at hand is whether we should support analogs in Data Prepper for both `field_split` and `field_split_pattern`, or if we should just support the more robust `field_split_pattern` (this is the current implementation).

**Comment by dlvenable** [comment]
We should at least support the `field_split` at least in the Logstash configuration converter. This is certainly possible since it supports customization of field conversion.

It does appear that this could be a valuable feature for users. And it is probably the same amount of work to support it in the regular Data Prepper pipeline configurations as it would be to convert using the Logstash configuration converter.

So I tend to think Data Prepper should have it.

A few changes I might like to see:
1. Perhaps name it `field_split_characters`. This gives a sense of parity between the features in my mind.
2. I think using a string and splitting on any string is not terribly obvious. I wonder if an array of characters would be appropriate. This could even allow for splitting on larger strings.

**Comment by dapowers87** [comment]
I am going to go ahead and add in the analog of `value_split` to this processor. 

One question is how do we handle it when `field_split_characters` and `field_delimiter_regex` are both defined? Logstash handles it by having `field_split_pattern` take precedence over `field_split`. Should we go that route or should we throw an error?

**Comment by graytaylor0** [comment]
I think the best user experience would be for us to require either `field_split_characters` or `field_delimiter_regex`, and throw a well defined configuration error saying that both can't be defined at once if the user configures this. For Logstash conversion where they define both, we can just drop the `field_split`.
