### ISSUE TITLE
Mutate, alter, and delete fields from Events

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#508]
Data Prepper should provide a Prepper or Preppers to support the following operations:

* Renaming fields
* Adding fields
* Deleting fields
* Copying fields

There should be one processor per action, e.g. a CopyProcessor, RenameProcessor, etc.

There should be one configuration, `skip_if_present`, that is defaulted to `false`. When set to `true`, the rename, add, and copy actions will not do any destructive behavior on existing data

**Comment by dlvenable** [comment]
Something worth discussing is the relationship between the Processor proposed in this proposal the string manipulation processor in #697 .

I envision that this processor be focused on generic mutations for keys and values. It shouldn't have to care about the underlying type. For example, moving a value from one key to another (ie. renaming) is independent of the type of value. I would like to see the string manipulation processor work only for keys with string values.

**Comment by dapowers87** [comment]
Should adding a field overwrite if the key already exists?

**Comment by dlvenable** [comment]
@dapowers87 , That's a good question. Perhaps this would be configurable?

**Comment by dapowers87** [comment]
@dlvenable - I can do that!

**Comment by dapowers87** [comment]
Seeing as how there is now `add_entry`, `copy_value`, `delete_entry`, and `rename_key` processors, should they support multiple actions per instance? At the moment only one is allowed... e.g.
```
copy_value:
  from_key: "message"
  to_key: "newMessage"
```

Should each of the processors do something like this?
```
copy_value:
  - ["message", "newMessage"]
  - ["otherEntry", "newEntry"]
```

**Comment by sbayer55** [comment]
It's a good idea! In my experience processors like `copy_value` are commonly used multiple times per pipeline.

In the configuration I'd recommend avoiding using fixed length lists to represent parameters based on position. Something list this could work nicely:
```
copy_values: 
  - 
    from_key: message
    to_key: newMessage
  - 
    from_key: otherEntry
    to_key: newEntry
```

For clarity in JSON that YAML would be this
```
{
  "copy_values": [
    {
      "from_key": "message",
      "to_key": "newMessage"
    },
    {
      "from_key": "otherEntry",
      "to_key": "newEntry"
    }
  ]
}
```

**Comment by dlvenable** [comment]
In general, I'd like to see Data Prepper configurations be more readable rather than use hidden conventions. So I'd still prefer using the `from_key`/`to_key` approach. So what @sbayer55  has sounds good.

But, I'm unsure if that will actually work. Currently Data Prepper always parses a plugin configuration as an object. Here you have a list. So I do think you will need something inbetween.

```
copy_values:
  copy:
    - from_key: message
       to_key: newMessage
    - from_key: otherEntry
       to_key newEntry
```

**Comment by dlvenable** [comment]
Also, I do like the idea of supporting this behavior in multiple plugins. I believe it can help with readability and could work nicely with the Conditional Routing concept from #1007.

**Comment by cmanning09** [comment]
With this change are we proposing the processors' names change as well?
