### ISSUE TITLE
Prepper for extracting dates from fields

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#509]
Provide a prepper which can extract dates from fields in events.

**Comment by asifsmohammed** [comment]
I looked into Logstash configurations on GitHub that have date filter. Almost all the configuration options are frequently used in 59,478 configuration files.

I'm planning to implement the following configurations

- locale (optional configuration)
- match 
- target (optional configuration, default value would be `event_timestamp`)
- timezone (optional configuration)

Configurations that are not being implemented are

- tag_on_failure

**Comment by dlvenable** [comment]
Thanks @asifsmohammed for proposing those configurations. Can you outline what each of them will do?

Also, let's try to be consistent in regard to our terminology. The `key_value` processor is using `destination` for the destination key name. It sounds like you are using `target`.

**Comment by dlvenable** [comment]
Also, for the date-specific configurations, I'd like to use the Java 8 time terminology. It is a very thorough time API. And by using the Java 8 terminology, we can make Data Prepper consistent in its time terminology.

**Comment by asifsmohammed** [comment]
Thanks for the feedback. I'll be consistent with the terminology and update it to `destination`. Also, I'll use Java time API.

**Comment by dlvenable** [comment]
Here are a few possible use-cases this processor can support:

* Read from a field with a date-time value set this as a date-time in the Event. This could be either a Java 8 `LocalDateTime` if no time zone is provided. If a time zone is provided, this would be an `OffsetDateTime`.
* Read from a field with a date value and set this as a date in the Event. This could use Java 8's `LocalDate`
* Read from a field with a time-only value. OpenSearch doesn't appear to have a time-only value. So how would this be handled? I think a reasonable default is to use the current date. This assumes the time came recently and the reporting system only reports times instead of dates and times.
* Read from two fields: One with a date-only and one with a time-only. Combine these into a single date-time and set a single field with that date-time.

Some scenarios that I don't believe are worth supporting at the current time:
* Partial dates: Getting a month and day is not something that is reasonably mapped into the current date.
* Partial times: Getting just a minute and second is not enough information and assuming the current hour is unreasonable. It is probably reasonable to support times with hour and minute only and then set the seconds to 0. Similarly with milliseconds.

**Comment by dlvenable** [comment]
@asifsmohammed , You proposed that the `match` field be a `Map<String, List<String>>`. What time would Data Prepper choose if two fields in the `Map` have times?

I think it would make sense to let the pipeline author define their own order of precedence. This could be done by changing `match` to a `List<DateMatch>` where `DateMatch` has both a `key` and `format`.

Here is an example.

```
match:
  - key: timestamp
     format: ["yyyy-MM-dd HH:mm:ss"]
  - key: received_date
     format: ["yyyy-MM-dd"]
```


The date processor would pick the first timestamp from the list, in the order the pipeline author specified.
