### ISSUE TITLE
Support ingesting json format data with keys mapping to the array element from source

### ISSUE THREAD

**Issue by Zhangxunmt** [opensearch-project/data-prepper#5134]
**Is your feature request related to a problem? Please describe.**
We want to utilize data prepper to ingest S3 files with json lines format like below. This is related to the offline batch ingestion that has been released in https://opensearch.org/docs/latest/ml-commons-plugin/api/async-batch-ingest/.

{ "content": ["Chapter 1", "Introduction"], "SageMakerOutput": ["Embedding1", "Embedding2"], "id":1 }
...
...

We need to ingest the above data into the KNN index with the following format: 
{
 "chapter": "$.content[0]",
 "title": "$.content[1]",
 "chapter_embedding": "$.SageMakerOutput[0]",
 "title_embedding": "$.SageMakerOutput[1]"},
 "id": "$.id"
}

However, there isn't a processor or combination of processors that could convert the source data into the final data format because currently data prepper does not support "json keys mapping to an array element". 

**Describe the solution you'd like**
Enhance the current list-to-map or map-to-list processors to allow mapping a key to an array element in the source. Or use a new processor to handle this request. 

**Describe alternatives you've considered (Optional)**
https://opensearch.org/docs/latest/ml-commons-plugin/api/model-apis/batch-predict/

**Additional context**
https://opensearch.org/docs/latest/ml-commons-plugin/api/async-batch-ingest/

**Comment by dlvenable** [comment]
This should perform the conversions you are looking for:

```
my-pipeline:
  ...
  processor:
    - copy_values:
        entries:
          - to_key: chapter
            from_key: /content/0
          - to_key: title
            from_key: /content/1
          - to_key: chapter_embedding
            from_key: /SageMakerOutput/0
          - to_key: title_embedding
            from_key: /SageMakerOutput/1
    - delete_entries:
        with_keys: [content, SageMakerOutput]

**Comment by dlvenable** [comment]
Also, for JSON lines inside an S3 object, you can make use of the `ndjson:` codec.

```
my-pipeline:
  source:
    s3:
      codec:
        ndjson:
```

This will treat each line as its own event and parse the JSON for that line to form the event.

**Comment by Zhangxunmt** [comment]
closed as the current strategy works.
