### ISSUE TITLE
[BUG] Data Prepper Enters OOM State and Stops Processing

### ISSUE THREAD

**Issue by Conklin-Spencer-bah** [opensearch-project/data-prepper#5172]
**Describe the bug**
We are using AWS OpenSearch Ingestion Service (OSIS) and have opened an enterprise support case to mirror this one. What we are seeing is that Data Prepper isn't properly handling load and enters an out of memory (OOM) state and crashes. 

We are able to see that document processing is successful until OOM state is reached, max memory and then the service hangs. This results in SQS being backed up with messages. If you restart the queue the messages will begin to de-queue and process, however it will then crash shortly after. 

The error message received is:
```
INFO  org.opensearch.dataprepper.core.breaker.HeapCircuitBreaker - Circuit breaker tripped and open. 6598691536 used memory bytes > 6442450944 configured
```

**To Reproduce**
1. Have an S3 -> SNS -> SQS Queue with a large volume of events. 
2. Start OpenSearch Ingestion Service with a set number of OCU's. (Ours was set to 8-12 however changing this doesn't appear to impact anything). 
3. Wait for memory to spike until maximum allowed memory is reached. 

**Expected behavior**
The expected behavior is that OpenSearch Ingestion Service will load balance based on the queued messages. Large quantities of queued messages should not dictate memory usage. Rather a reduction in de-queue rate. I expect the service to operate as Log Stash which will handle messages within a limit and only pull from the SQS queue when it is able to. 

What seems to be happening is that data prepper is overloading itself by pulling more SQS messages than it is able to handle. 

**Screenshots**

Memory spiked
<img width="762" alt="Screenshot 2024-11-06 at 10 01 32 AM" src="https://github.com/user-attachments/assets/6cc09500-1856-43a3-95a6-fd31da6ae45f">

Document write spikes on start, then stops. 
<img width="806" alt="Screenshot 2024-11-06 at 1 11 18 PM" src="https://github.com/user-attachments/assets/65f1a1ac-8edc-4e0d-8e2d-1aadc7800394">

**Environment (please complete the following information):**
AWS Managed OpenSearch Ingestion Service

**Additional context**

**Comment by sb2k16** [comment]
@Conklin-Spencer-bah - Could you please share the pipeline configuration for this test.

**Comment by Conklin-Spencer-bah** [comment]
@sb2k16 thanks for the reply. This ended up being an issue within AWS Managed OpenSearch. It put write blocks on the index and didn't report it. I'm going to close this as when I resolved that issue everything cleared up on the pipeline side.
