### ISSUE TITLE
Deprecate Records

### ISSUE THREAD

**Issue by cmanning09** [opensearch-project/data-prepper#547]
As part of the migration to the new model `Record`s should be replaced with `Event`s.  All interfaces, abstract classes and plugins should be updated to support only `Event`s. `Record` and `RecordMetadata`s should be removed from the code base.

This will be a breaking change and should be introduced in the next major version 2.0.

Related to new Model Proposal: #319

**Comment by dlvenable** [comment]
Issue #946 supersedes this issue. And the final removal will be done in #944.
