### ISSUE TITLE
Processor to filter out (remove/drop) entire events

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#598]
Data Prepper should provide a processor which removes entire events. This processor need not take any special input, but does require conditional support from #522. (Otherwise every event would be dropped).

**Outstanding Questions**

What name should this processor have?

**Comment by graytaylor0** [comment]
`drop` seems fine but `drop_events` might be a little better.

**Comment by dlvenable** [comment]
I agree on `drop_events`. It is much clearer on what it does, since it could be unclear as to whether it drops events or specific fields.
