### ISSUE TITLE
FileSink to use Event model

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#606]
**Is your feature request related to a problem? Please describe.**
Follow up on Event model change #538 to migrate the [FileSink](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/sink/FileSink.java). 

**Describe the solution you'd like**
This sink should implement should utilized events: `... implements Sink<Record<Event>> {`

**Additional context**
This plugin will move to only `Event`'s when the `Record`is fully deprecated in v2.0

**Comment by cmanning09** [comment]
updated description
