### ISSUE TITLE
NoOpPrepper to use Event model

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#607]
**Is your feature request related to a problem? Please describe.**
Follow up on Event model change #538 for the [NoOpPrepper](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/prepper/NoOpPrepper.java)

**Describe the solution you'd like**
This processor is a generic and should be moved to using `Record<Event>`

**Additional context**
This plugin will move to only `Event`'s when the `Record`is fully deprecated in v2.0

**Comment by cmanning09** [comment]
I added more detail to the description.
