### ISSUE TITLE
Remove support for deprecated Prepper plugins

### ISSUE THREAD

**Issue by sbayer55** [opensearch-project/data-prepper#619]
**Is your feature request related to a problem? Please describe.**
Remove ambiguity in pipeline configuration YAML files and Plugins by supporting a single name for Processors/Preppers.

**Describe the solution you'd like**
Remove support for the the `Prepper` plugin type and remove support for the prepper name within the pipeline configuration YAML.

**Describe alternatives you've considered (Optional)**
n/a

**Additional context**
This change will be dependent on all DataPrepper provided plugins migrating to the new Processor plugin type.

**Tasks**

- [x] Remove Prepper plugin support in code (PR #1707)
- [x] Update usage of `prepper:` to `processor:` in OpenSearch Documentation website (PR: https://github.com/opensearch-project/documentation-website/pull/1056)

**Comment by dlvenable** [comment]
We currently support either of the following configurations:

```
prepper:
  - copy_value:
  - delete_value
```

```
processor:
  - copy_value:
  - delete_value
```

After this change we will only support `processor`.

**Comment by dlvenable** [comment]
We should also search the code base for any samples, tests, or documentation that is still using the deprecated `preppers:`. These should all be changed to use `processor:` instead.

**Comment by cmanning09** [comment]
@dlvenable is [PrepperState](https://github.com/opensearch-project/data-prepper/blob/eb94f4abbd4f83ce3b3ebe4d4478af7531f9bc36/data-prepper-api/src/main/java/com/amazon/dataprepper/prepper/state/PrepperState.java) a part of the `Prepper` deprecation? I am concerned we may have missed providing a migration path.

**Comment by dlvenable** [comment]
We should remove this as well. Ideally, we would have added a deprecation path here. But, I believe it only affects plugin authors, not end user. So I think we should go ahead and rename it.

**Comment by oeyh** [comment]
@cmanning09 @dlvenable Thanks for looking into it!

PrepperState is implemented by [MapDbPrepperState](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/mapdb-prepper-state/src/main/java/com/amazon/dataprepper/plugins/prepper/state/MapDbPrepperState.java), so I assume this should be renamed to MapDbProcessorState as well? I will add those changes to the open PR #1707. 

There will still be plugins, classes, and variables still with "prepper" in their names (mostly in `data-prepper-plugins`). For those, I will open an issue in case we want to do a thorough cleanup in the future.

**Comment by dlvenable** [comment]
I think we can rename those as part of 2.0. They names visible to pipeline authors do not have `prepper` in them, so we are just renaming class names.

**Comment by oeyh** [comment]
Follow-up issue was created (#1730). Close this one.
