### ISSUE TITLE
Update Deployment Scripts to use OpenSearch or Remove Obsolete Scripts

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#639]
**Is your feature request related to a problem? Please describe.**

Data Prepper has several deployment scripts and examples. Some of these have updated to use OpenSearch, but some are still using OpenDistro for ElasticSearch.

**Describe the solution you'd like**

Update these to run using OpenSearch. Also include updates to the documentation for those scripts.

Or remove any obsolete scripts or examples.

**Additional context**

This is somewhat related to #638.

**Comment by jianghancn** [comment]
EC2 Deployment CloudFormation template cannot be upgraded to OpenSearch version of Data Pepper because there is no OpenSearch/DataPrepper release for Linux at this time point.

**Comment by dlvenable** [comment]
I also found that Data Prepper has the following sample.
https://github.com/opensearch-project/data-prepper/blob/main/examples/kibana-trace-analytics/Dockerfile

It is extremely sparse and there is no README. Can we delete it?

**Comment by chenqi0805** [comment]
> I also found that Data Prepper has the following sample. https://github.com/opensearch-project/data-prepper/blob/main/examples/kibana-trace-analytics/Dockerfile
> 
> It is extremely sparse and there is no README. Can we delete it?

@dlvenable I agree we should be able to delete that. This is pretty outdated as at that time the trace-analytics plugin has not been built into the OpenSearch-dashboard (Kibana).
