### ISSUE TITLE
Add API in JacksonEvent builder to support creation from raw text string

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#646]
**Is your feature request related to a problem? Please describe.**
Split from #625 . We have manually assigned constant MESSAGE_KEY="message" as key for creating JacksonEvent out of raw string in 3 different sources. 

**Describe the solution you'd like**
JacksonEvent builder should expose an API to cover that.

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by cmanning09** [comment]
This does not appear to be complete after reviewing this implementation. The functionality is package protected and not leveraged in our code base.
