### ISSUE TITLE
Update to Gradle 7

### ISSUE THREAD

**Issue by reta** [opensearch-project/data-prepper#662]
**Is your feature request related to a problem? Please describe.**
The OpenSearch Plugins are still built using Gradle 6.6.x whereas the Gradle release train has moved to 7.x already. The OpenSearch core is about to be switched to Gradle 7.3 (see please opensearch-project/OpenSearch#1609), it would make sense to switch all plugins to Gradle 7.3 as well.

**Describe the solution you'd like**
 Update Gradle to 7.3

**Describe alternatives you've considered (Optional)**
N/A

**Additional context**
See please opensearch-project/OpenSearch#1246 and opensearch-project/opensearch-plugins#107

**Comment by dlvenable** [comment]
Data Prepper releases on a different schedule from OpenSearch. Thus, Data Prepper will need to wait until the fix is in a version of OpenSearch which is released in Maven Central.

**Comment by reta** [comment]
@dlvenable do you think it makes sense to branch of `1.x` and switch `main` to 2.0? (like k-NN plugin fe [1])?

[1] https://github.com/opensearch-project/k-NN/pull/301

**Comment by dlvenable** [comment]
@reta , No, not for Data Prepper. Data Prepper is an independent application and releases independently of OpenSearch. Data Prepper does use OpenSearch artifacts from Maven though. The reason we are currently blocked from updating to Gradle 7 is that one of our sub-projects uses the OpenSearch build-tools to run integration tests against OpenSearch. So we either have to: 1) Break that coupling; or 2) wait for OpenSearch 2.0.0 to release to Maven Central.

**Comment by dblock** [comment]
@dlvenable It would be good to build Data Prepper against OpenSearch 2.0 -SNAPSHOT _before_ that gets released for any potential bugs.

**Comment by dlvenable** [comment]
@dblock , We can at least run some local builds against that snapshot to verify that Data Prepper can run Gradle 7 with this change. I don't want to use a `SNAPSHOT` for normal builds however since Data Prepper does have a distinct release schedule than OpenSearch.
