### ISSUE TITLE
Linux Archives for Data Prepper Releases.

### ISSUE THREAD

**Issue by cmanning09** [opensearch-project/data-prepper#696]
**Is your feature request related to a problem? Please describe.**
I would like to run docker on a dedicated machine and not a docker container. 

**Describe the solution you'd like**
I would like the latest version of Data prepper as a tarball to install on dedicated host.

**Additional context**
ODFE supported Linux Archives for Data Prepper. See: [ODFE Downloads Page](https://opendistro.github.io/for-elasticsearch/downloads.html#ingest)

**Comment by dlvenable** [comment]
For Data Prepper 1.2.1, Data Prepper will have a Linux archive available as a tar.gz file. It will have two alternatives - 1) without a JDK; 2) with a bundled JDK.

**Comment by anirudhbagri** [comment]
Hi @dlvenable, 

I see v1.2.1 release, but where can I download the linux distribution of data-prepper from?

**Comment by dlvenable** [comment]
@anirudhbagri , I am currently working on this and will update this issue with the links once they are ready.

**Comment by dlvenable** [comment]
@anirudhbagri , The Data Prepper 1.2.1 archives for Linux are now available for download at https://opensearch.org/downloads.html. Search for "Data Prepper" and then choose the Linux platform from the drop-down.

**Comment by dlvenable** [comment]
Data Prepper archives are available:

Standard distribution:
https://artifacts.opensearch.org/data-prepper/1.2.1/opensearch-data-prepper-jdk-1.2.1-linux-x64.tar.gz
https://artifacts.opensearch.org/data-prepper/1.2.1/opensearch-data-prepper-jdk-1.2.1-linux-x64.tar.gz.sig

Without bundled JDK:
https://artifacts.opensearch.org/data-prepper/1.2.1/opensearch-data-prepper-1.2.1-linux-x64.tar.gz
https://artifacts.opensearch.org/data-prepper/1.2.1/opensearch-data-prepper-1.2.1-linux-x64.tar.gz.sig
