### ISSUE TITLE
String Manipulation Processor

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#697]
Data Prepper should have a Processor for string manipulation.

Some candidate operations:

* `uppercase` - Make a string all uppercase
* `lowercase` - Make a string all lowercase
* `trim` - Trim whitespace from the start and end of a string
* `split` - Split a string on a delimiter into an array of strings
* `join` - Create a new string from other fields, separated by a delimiter
* `format` - Create a new string from a format string and other values in an event

This should be a new Processor. It can also deprecate the existing `string_converter` plugin. Unlike the existing `string_converter` processor, this new processor will rely on updating keys. See https://github.com/opensearch-project/data-prepper/pull/753/files#r770751733 for more information on the difference between the plugins.

**Comment by oridool** [comment]
@dlvenable ,
Perhaps the approach can be embedding a javascript engine such as:
https://www.oracle.com/technical-resources/articles/java/jf14-nashorn.html
With this, any manipulation can be done.
