### ISSUE TITLE
Create an Aggregate Processor for Single Node Data Prepper

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#829]
**Is your feature request related to a problem? Please describe.**
Data Prepper users need a processor that can be utilized for generic stateful aggregation

**Describe the solution you'd like**
A solution has already been proposed in RFC #699 

# Tasks

* [x] #838
* [x] #844
* [x] #871
* [x] #938
* [x] #1004
* [x] #1038

**Comment by dlvenable** [comment]
Data Prepper 1.3.0 will not save state for the aggregate processor. This work is postponed and moved into #985 .

**Comment by dlvenable** [comment]
I have added the #1130 issue for an enhancement which allows pipeline authors to conclude groups early. The aggregate Process doesn't strictly need this feature. So, we can consider the aggregate feature complete on its own.
