### ISSUE TITLE
Remove jcenter repository

### ISSUE THREAD

**Issue by mch2** [opensearch-project/data-prepper#870]
## Description
JCenter has been turned off and should be removed as a referenced repository.

Please Remove any direct dependency on jcenter() within a repositories block in gradle files.

Related: https://github.com/opensearch-project/opensearch-build/issues/1456

**Comment by dlvenable** [comment]
We removed JCenter from Data Prepper sometime ago. And we fixed issues related to the Gradle Plugin portal's dependency on JCenter in #859 today.
