### ISSUE TITLE
Potential KeyValueProcessor feature: tag_on_failure

### ISSUE THREAD

**Issue by dapowers87** [opensearch-project/data-prepper#886]
When a kv operation causes a runtime exception to be thrown within the processor, the operation is safely aborted without crashing the processor, and the event is tagged with the provided value.

Default is `keyvalueprocessor_failure`

See: https://www.elastic.co/guide/en/logstash/current/plugins-filters-kv.html#plugins-filters-kv-tag_on_failure

**Comment by dlvenable** [comment]
This requires #629 first. And it is another good reason for us to include a tagging related feature.

**Comment by graytaylor0** [comment]
Relevant links for example of adding tags on json parse failure in the `parse_json` processor

* https://github.com/opensearch-project/data-prepper/blob/3d8d01babf1e4822926f260fa24ca95f69ea6d9f/data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessor.java#L56
* https://github.com/opensearch-project/data-prepper/blob/3d8d01babf1e4822926f260fa24ca95f69ea6d9f/data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessor.java#L92
