### ISSUE TITLE
Potential KeyValueProcessor feature: include_keys

### ISSUE THREAD

**Issue by dapowers87** [opensearch-project/data-prepper#887]
An array specifying the parsed keys which should be added to the event. By default all keys will be added.

See: https://www.elastic.co/guide/en/logstash/current/plugins-filters-kv.html#plugins-filters-kv-include_keys

**Comment by evheniyt** [comment]
This is a really important feature that is blocking us from migrating an old logstash implementation to a data-prepper. Logs could contain a lot of different key-values pairs and we need to filter only specific keys.

**Comment by dlvenable** [comment]
@evheniyt ,

Thanks for your feedback on this issue. We are happy to receive PRs. Would you be interested in contributing this feature? 

If so, please see the https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md guide. And this is the sub-project with the code for this processor: https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins/key-value-processor
