### ISSUE TITLE
Performance test and profiling on trace ingestion post migration to event model

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#939]
**Is your feature request related to a problem? Please describe.**
All trace ingestion pipeline plugins have now been using event model in a side branch https://github.com/opensearch-project/data-prepper/tree/maint/546-migrate-trace-analytics-to-event-model. As essential task of #546 , we need performance testing on the pipeline after migration to benchmark against the pipeline before migration (main branch) and profiling on any potential bottlenecks in implementation

**Describe the solution you'd like**
The high-level goal is to

* benchmark performance against before migration
* profiling on bottlenecks.

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by dlvenable** [comment]
Closed in #1041 and #1044
