### ISSUE TITLE
An Interface for GroupState

### ISSUE THREAD

**Issue by cmanning09** [opensearch-project/data-prepper#942]
**Is your feature request related to a problem? Please describe.**
GroupState was defined as a `Map<Object, Object>` as part the Stateful Aggregation RFC #699. The groupState is part of the AggregateAction Interface and will establish a contract with plugin developers for interacting with the groupState. This is a one way door decision that will couple the groupState to the map interface. Maybe not completely one way door but it would require a breaking change to extend group state beyond the map interface. Limiting our ability to extend the groupState beyond just a `Map<Object,Object>`. 

**Describe the solution you'd like**
I would like us to consider defining a data type to encapsulate the groupState. This will give us the ability to extend the existing design without introducing a breaking change.

**Describe alternatives you've considered (Optional)**
Open to alternatives or other suggestions.

**Comment by cmanning09** [comment]
I believe this was overlooked initially. I would like to raise the point for discussion and make an explicit decision

**Comment by dlvenable** [comment]
This is a good discussion point.

The original intention for the aggregate processor is that `groupState` is an arbitrary map. Only the AggregateAction really cares what happens in that Map. So I'm unsure what else would be present on the `groupState`.

----

I do have a concern with the current interface. If actions eventually want additional information beyond the `groupState`, we'd have to break the interface. The current interface is:

```
default AggregateActionResponse handleEvent(final Event event, final Map<Object, Object> groupState)
```

Maybe what is missing is a wrapper around the `groupState`. Here is a possible solution:

```
interface AggregateGroupInput {
  Map<Object, Object> getGroupState();
}
```

```
default AggregateActionResponse handleEvent(final Event event, final AggregateGroupInput input)
```

Then actions can still get the `groupState`, but they can also get other data in the future?

----

Or, do you mean to have a new class like `GroupState extends Map<Object, Object>`?

**Comment by graytaylor0** [comment]
If we really want to allow extension for both performing operations on the GroupState as well as extension for providing additional information to the `AggregateAction`, then we could combine the two approaches outlined by @dlvenable 

```
interface AggregateActionInput {
  GroupState getGroupState();
}
```

```
class GroupState extends HashMap<Object, Object>
```

**Comment by dlvenable** [comment]
@graytaylor0 , I do believe we could combine them. But, `GroupState` should be an interface and should extend `Map`. It definitely shouldn't be tied to a specific `Map` implementation.

But, I'm still somewhat unsure if the map itself ever needs to expand beyond just a map.

**Comment by graytaylor0** [comment]
@dlvenable so what would the actual implementation of `GroupState` look like? Something like this?

`class DefaultGroupState implements GroupState extends HashMap`

We don’t want to Override all the Map interface functions for no reason.

**Comment by dlvenable** [comment]
@graytaylor0 , Yes, that is the approach I'd take. Just keep the `DefaultGroupState` package private.

**Comment by graytaylor0** [comment]
Ok. Is everyone in agreement to move forward with this approach?
