### ISSUE TITLE
Deprecate Records

### ISSUE THREAD

**Issue by cmanning09** [opensearch-project/data-prepper#946]
Related to #319 and and a prerequisite to #944 

The `Record` and `RecordMetadata `classes should be marked with `@Deprecated` annotation.

**Comment by mohitsaxenaknoldus** [comment]
Can I work on this?

**Comment by dlvenable** [comment]
@mohitsaxenaknoldus ,

Thanks for reaching out to help! Yes, this is something you can work on.

Please be sure to read the [Contribution Guide](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md) before starting on it. Be sure you sign your Git commits as noted in the Contribute Guide.

There is also a [Developer Guide](https://github.com/opensearch-project/data-prepper/blob/main/docs/developer_guide.md) to help you get up and running.

**Comment by mohitsaxenaknoldus** [comment]
Thanks, here's the PR: https://github.com/opensearch-project/data-prepper/pull/954
