### ISSUE TITLE
Default AggregateProcessor behavior compares full Events

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#974]
**Is your feature request related to a problem? Please describe.**
Currently, the `AggregateProcessor` requires a non-empty list of `identificationKeys` to decide which `AggregateGroup` an Event is placed in. As a user that wants to simply remove any duplicate Events, this is a pain to configure.

**Describe the solution you'd like**
If no `identificationKeys` are configured for an `aggregate` processor, the default behavior could be to put all Events in the same group.

**Concerns**
A concern with this approach is that the Peer Forwarder (#700) may be difficult to integrate with this behavior, since it would have to choose a random AggregateProcessor to send to.

Another concern is that a single group may result in unintended performance issues for the user, as there would be a lot more locking

**Alternatives**
1. Instead of throwing a configuration error, simply have the default `identificationKey` of `message`
2. Have the default behavior be to compare all keys of an Event and put them into a group. This would also be difficult to integrate with the Peer Forwarder, and could potentially result in high memory usage as many groups would be made.

**Comment by dlvenable** [comment]
Combining all events into one group would be problematic in clusters since peer forwarding would not be available.

As I understand it, duplicates are detected only on a subset of fields. Thus the `identificationKeys` would determine that subset. I'm not sure if there are any default values that Data Prepper could provide here. It might be possible with a strict OTel model and that is something we could consider.

**Comment by graytaylor0** [comment]
Thanks for the response @dlvenable. Yes the Peer forwarder integration is the main concern here. However, if the Peer forwarder were able to hash an entire Event if it notices that there are no `identificationKeys`, it could work. However, the effort may not be worth the result, and it may make sense to require `identificationKeys` at least until there is a request for such a feature.

**Comment by graytaylor0** [comment]
I am closing this issue as there is no reason to change the requiring of `identification_keys` at this time.
