### ISSUE TITLE
Support Multi-node aggregation by integrating it with the Peer Forwarder

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#978]
The `aggregate` processor as implemented for Data Prepper 1.3.0 will only support single-node deployments. Integrating it into the core Peer Forwarder (#700) will allow it to work with multiple nodes.

**Comment by dlvenable** [comment]
This feature depends on #1189 since the AggregateProcessor is very intentionally not `@SingleThread`.

**Comment by asifsmohammed** [comment]
Integrated aggregate processor with core peer forwarder as part of this PR. https://github.com/opensearch-project/data-prepper/pull/1767
